### ISSUE TITLE
Model convert fails for yolov5_x

### ISSUE THREAD

**Issue by xingyueye** [open-mmlab/mmyolo#101]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmyolo/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmyolo.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmyolo).

### 🐞 Describe the bug

Hi, I want to convert yolov5x.pt to mmyolo with
`python tools/model_converters/yolov5_to_mmyolo.py --src ../models/yolov5x.pt --dst ../models/mmyolov5x.pt`
But error occurs like this:
```
Traceback (most recent call last):
  File "tools/model_converters/yolov5_to_mmyolo.py", line 77, in <module>
    main()
  File "tools/model_converters/yolov5_to_mmyolo.py", line 73, in main
    convert(args.src, args.dst)
  File "tools/model_converters/yolov5_to_mmyolo.py", line 33, in convert
    yolov5_model = torch.load(src)['model']
  File "xxx/anaconda3/envs/mm2_cu11/lib/python3.8/site-packages/torch/serialization.py", line 607, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "xxx/anaconda3/envs/mm2_cu11/lib/python3.8/site-packages/torch/serialization.py", line 882, in _load
    result = unpickler.load()
  File "xxx/envs/mm2_cu11/lib/python3.8/site-packages/torch/serialization.py", line 875, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'models'

```

### Environment

My env list:
```
Package            Version   Editable project location
------------------ --------- ----------------------------------------------------------------------------------
addict             2.4.0
albumentations     1.0.1
certifi            2022.9.14
charset-normalizer 2.1.1
click              8.1.3
colorama           0.4.5
commonmark         0.9.1
contourpy          1.0.5
cycler             0.11.0
fonttools          4.37.3
idna               3.4
imageio            2.22.0
importlib-metadata 4.12.0
kiwisolver         1.4.4
Markdown           3.4.1
matplotlib         3.6.0
mkl-fft            1.3.1
mkl-random         1.2.2
mkl-service        2.4.0
mmcv               2.0.0rc1
mmdet              3.0.0rc1
mmengine           0.1.0
mmyolo             0.1.0     xxx/infra-mt-cvzoo-yolo
model-index        0.1.11
networkx           2.8.6
numpy              1.23.1
opencv-python      4.6.0.66
openmim            0.3.2
ordered-set        4.1.0
packaging          21.3
pandas             1.5.0
Pillow             9.2.0
pip                22.1.2
pycocotools        2.0.5
Pygments           2.13.0
pyparsing          3.0.9
python-dateutil    2.8.2
pytz               2022.2.1
PyWavelets         1.4.1
PyYAML             6.0
requests           2.28.1
rich               12.5.1
scikit-image       0.19.3
scipy              1.9.1
setuptools         63.4.1
six                1.16.0
tabulate           0.8.10
termcolor          2.0.1
terminaltables     3.1.10
tifffile           2022.8.12
torch              1.10.1
torchvision        0.11.2
tqdm               4.64.1
typing_extensions  4.3.0
urllib3            1.26.12
wheel              0.37.1
yapf               0.32.0
zipp               3.8.1
```

**Comment by hhaAndroid** [comment]
![image](https://user-images.githubusercontent.com/17425982/192803829-7bc04d60-f855-40cf-ae24-42690bc6c835.png)
