### ISSUE TITLE
ValueError: Key img_path is not in available keys. Unable to find a solution.

### ISSUE THREAD

**Issue by Lucky-person** [open-mmlab/mmyolo#1010]
Original Traceback (most recent call last):
  File "D:\Anaconda\envs\mmyolo\lib\site-packages\torch\utils\data\_utils\worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "D:\Anaconda\envs\mmyolo\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\Anaconda\envs\mmyolo\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\Anaconda\envs\mmyolo\lib\site-packages\mmengine\dataset\base_dataset.py", line 410, in __getitem__
    data = self.prepare_data(idx)
  File "D:\openmmlab\mmyolo\mmyolo\datasets\yolov5_coco.py", line 53, in prepare_data
    return self.pipeline(data_info)
  File "D:\Anaconda\envs\mmyolo\lib\site-packages\mmengine\dataset\base_dataset.py", line 60, in __call__
    data = t(data)
  File "D:\Anaconda\envs\mmyolo\lib\site-packages\mmcv\transforms\base.py", line 12, in __call__
    return self.transform(results)
  File "D:\Anaconda\envs\mmyolo\lib\site-packages\mmdet\structures\bbox\box_type.py", line 267, in wrapper
    return func(self, results)
  File "D:\Anaconda\envs\mmyolo\lib\site-packages\mmdet\datasets\transforms\transforms.py", line 1699, in transform
    results = self.aug(**results)
  File "D:\Anaconda\envs\mmyolo\lib\site-packages\albumentations\core\composition.py", line 255, in __call__
    self._check_args(**data)
  File "D:\Anaconda\envs\mmyolo\lib\site-packages\albumentations\core\composition.py", line 324, in _check_args
    raise ValueError(msg)
ValueError: Key img_path is not in available keys.

**Comment by Lucky-person** [comment]
Follow the operation process of 15 minutes object detection throughout the entire process

**Comment by yuexiayiren159** [comment]
View your albumentations version,Changed the version to 1.3.1 and it worked

**Comment by GIBI1557** [comment]
thank you very much!!!!

> View your albumentations version,Changed the version to 1.3.1 and it worked
