### ISSUE TITLE
Build Error:   AttributeError: 'MinimalDistribution' object has no attribute '_referenced_files'

### ISSUE THREAD

**Issue by TonyCongqianWang** [open-mmlab/mmyolo#1020]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmyolo/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmyolo.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmyolo).

### 🐞 Describe the bug

I tried to install mmyolo in different ways. I tried using the guide from [here](https://mmyolo.readthedocs.io/en/latest/get_started/installation.html#best-practices) but then I received a CUDA version mismatch. When I follow the instructions on github. I get 
``` 
Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "/home/Tony/mmyolo/setup.py", line 160, in <module>
      setup(
    File "/home/anaconda3/envs/mmyolo/lib/python3.8/site-packages/setuptools/__init__.py", line 154, in setup
      _install_setup_requires(attrs)
    File "/home/anaconda3/envs/mmyolo/lib/python3.8/site-packages/setuptools/__init__.py", line 146, in _install_setup_requires
      dist.parse_config_files(ignore_option_errors=True)
    File "/home/anaconda3/envs/mmyolo/lib/python3.8/site-packages/setuptools/dist.py", line 804, in parse_config_files
      parse_configuration(
    File "/home/anaconda3/envs/mmyolo/lib/python3.8/site-packages/setuptools/config/__init__.py", line 37, in _wrapper
      return fn(*args, **kwargs)
    File "/home/anaconda3/envs/mmyolo/lib/python3.8/site-packages/setuptools/config/setupcfg.py", line 191, in parse_configuration
      distribution._referenced_files.update(
  AttributeError: 'MinimalDistribution' object has no attribute '_referenced_files'
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
```
when running
`mim install -v -e .
`

### Environment

Can collect due to not being able to install mmyolo

**Comment by ailihong** [comment]
pip uninstall setuptools

and then:

pip install setuptools

This works for me and fixes my issue.
