### ISSUE TITLE
error installing 

### ISSUE THREAD

**Issue by addisflava** [open-mmlab/mmyolo#1025]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmyolo/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmyolo.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmyolo).

### 🐞 Describe the bug

mim install -v -e .
Traceback (most recent call last):
  File "/home/d/miniconda3/envs/test/bin/mim", line 5, in <module>
    from mim.cli import cli
  File "/home/d/miniconda3/envs/test/lib/python3.12/site-packages/mim/__init__.py", line 10, in <module>
    import setuptools  # noqa: F401
    ^^^^^^^^^^^^^^^^^
  File "/home/d/miniconda3/envs/test/lib/python3.12/site-packages/setuptools/__init__.py", line 16, in <module>
    import setuptools.version
  File "/home/d/miniconda3/envs/test/lib/python3.12/site-packages/setuptools/version.py", line 1, in <module>
    import pkg_resources
  File "/home/d/miniconda3/envs/test/lib/python3.12/site-packages/pkg_resources/__init__.py", line 2172, in <module>
    register_finder(pkgutil.ImpImporter, find_on_path)
                    ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?

(test) d@d:~/parking/backend$ mim install "mmdet>=3.0.0,<4.0.0"
Traceback (most recent call last):
  File "/home/d/miniconda3/envs/test/bin/mim", line 5, in <module>
    from mim.cli import cli
  File "/home/d/miniconda3/envs/test/lib/python3.12/site-packages/mim/__init__.py", line 10, in <module>
    import setuptools  # noqa: F401
    ^^^^^^^^^^^^^^^^^
  File "/home/d/miniconda3/envs/test/lib/python3.12/site-packages/setuptools/__init__.py", line 16, in <module>
    import setuptools.version
  File "/home/d/miniconda3/envs/test/lib/python3.12/site-packages/setuptools/version.py", line 1, in <module>
    import pkg_resources
  File "/home/d/miniconda3/envs/test/lib/python3.12/site-packages/pkg_resources/__init__.py", line 2172, in <module>
    register_finder(pkgutil.ImpImporter, find_on_path)
                    ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
(test) d@d:~/parking/backend$ mim install mmdet
Traceback (most recent call last):
  File "/home/d/miniconda3/envs/test/bin/mim", line 5, in <module>
    from mim.cli import cli
  File "/home/d/miniconda3/envs/test/lib/python3.12/site-packages/mim/__init__.py", line 10, in <module>
    import setuptools  # noqa: F401
    ^^^^^^^^^^^^^^^^^
  File "/home/d/miniconda3/envs/test/lib/python3.12/site-packages/setuptools/__init__.py", line 16, in <module>
    import setuptools.version
  File "/home/d/miniconda3/envs/test/lib/python3.12/site-packages/setuptools/version.py", line 1, in <module>
    import pkg_resources
  File "/home/d/miniconda3/envs/test/lib/python3.12/site-packages/pkg_resources/__init__.py", line 2172, in <module>
    register_finder(pkgutil.ImpImporter, find_on_path)
                    ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
(test) d@d:~/parking/backend$ mim install mmengine
Traceback (most recent call last):
  File "/home/d/miniconda3/envs/test/bin/mim", line 5, in <module>
    from mim.cli import cli
  File "/home/d/miniconda3/envs/test/lib/python3.12/site-packages/mim/__init__.py", line 10, in <module>
    import setuptools  # noqa: F401
    ^^^^^^^^^^^^^^^^^
  File "/home/d/miniconda3/envs/test/lib/python3.12/site-packages/setuptools/__init__.py", line 16, in <module>
    import setuptools.version
  File "/home/d/miniconda3/envs/test/lib/python3.12/site-packages/setuptools/version.py", line 1, in <module>
    import pkg_resources
  File "/home/d/miniconda3/envs/test/lib/python3.12/site-packages/pkg_resources/__init__.py", line 2172, in <module>
    register_finder(pkgutil.ImpImporter, find_on_path)
                    ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?

### Environment

conda install pytorch torchvision cpuonly -c pytorch

### Additional information

c

**Comment by coltarm** [comment]
Hello, I am confronted with the same problem. Did you find a solution?

edit : I fixed it. I saw that the version installed in my conda environment was python 3.12. I don't know why because I follow the guides on the github : https://github.com/open-mmlab/mmyolo/tree/main?tab=readme-ov-file and the version specified was python 3.8.
There seems to be a problem with python 3.12.
https://stackoverflow.com/questions/77364550/attributeerror-module-pkgutil-has-no-attribute-impimporter-did-you-mean

I just changed python 3.8 by python 3.9, and it installed the right python version
