### ISSUE TITLE
raise KeyError(f'Cannot get key by value "{value}" of {cls}')

### ISSUE THREAD

**Issue by mylittlebuds** [open-mmlab/mmyolo#282]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmyolo/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmyolo.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmyolo).

### 🐞 Describe the bug

hello friends:

please check log as below:

python tools/deploy.py configs/mmdet/detection/detection_onnxruntime_static_O.py /home/ubuntu/PycharmProjects/MMDeploy/mmyolo/configs/yolox/yolox_s_8xb8-300e_coco.py /home/ubuntu/PycharmProjects/mdforpretrain/yolox_s_8xb8-300e_coco_20220917_030738-d7e60cb2.pth /home/ubuntu/PycharmProjects/mmpose-master/tests/data/coco/wanyubin-R-2_601272.jpg --work-dir mmdeploy_model/yolox_s_v2 --device cpu --dump-info
Traceback (most recent call last):
  File "tools/deploy.py", line 448, in <module>
    main()
  File "tools/deploy.py", line 130, in main
    device=args.device)
  File "/home/ubuntu/PycharmProjects/MMDeploy/mmdeploy/backend/sdk/export_info.py", line 407, in export2SDK
    pipeline_info = get_pipeline(deploy_cfg, model_cfg, work_dir, device)
  File "/home/ubuntu/PycharmProjects/MMDeploy/mmdeploy/backend/sdk/export_info.py", line 345, in get_pipeline
    preprocess = get_preprocess(deploy_cfg, model_cfg, device)
  File "/home/ubuntu/PycharmProjects/MMDeploy/mmdeploy/backend/sdk/export_info.py", line 219, in get_preprocess
    pipeline = task_processor.get_preprocess()
  File "/home/ubuntu/PycharmProjects/MMDeploy/mmdeploy/codebase/mmdet/deploy/object_detection.py", line 294, in get_preprocess
    model_cfg = process_model_config(self.model_cfg, [''], input_shape)
  File "/home/ubuntu/PycharmProjects/MMDeploy/mmdeploy/codebase/mmdet/deploy/object_detection.py", line 53, in process_model_config
    cfg.data.test.pipeline = replace_ImageToTensor(cfg.data.test.pipeline)
  File "/home/ubuntu/anaconda3/envs/openmm37clone/lib/python3.7/site-packages/mmcv/utils/config.py", line 48, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'data'

### Environment

os:ubuntu18.04
python:3.7
2022-11-14 21:02:13,562 - mmdeploy - INFO - TorchVision: 0.11.3+cu113
2022-11-14 21:02:13,562 - mmdeploy - INFO - OpenCV: 4.6.0
2022-11-14 21:02:13,562 - mmdeploy - INFO - MMCV: 1.3.18
2022-11-14 21:02:13,562 - mmdeploy - INFO - MMCV Compiler: GCC 7.3
2022-11-14 21:02:13,562 - mmdeploy - INFO - MMCV CUDA Compiler: 11.3
2022-11-14 21:02:13,562 - mmdeploy - INFO - MMDeploy: 0.9.0+b6f8c1c
2022-11-14 21:02:13,562 - mmdeploy - INFO - 

2022-11-14 21:02:13,562 - mmdeploy - INFO - **********Backend information**********
2022-11-14 21:02:14,177 - mmdeploy - INFO - onnxruntime: 1.8.1  ops_is_avaliable : True
2022-11-14 21:02:14,204 - mmdeploy - INFO - tensorrt: 8.4.3.1   ops_is_avaliable : False
2022-11-14 21:02:14,219 - mmdeploy - INFO - ncnn: 1.0.20221027  ops_is_avaliable : True

### Additional information

no mater detection_onnxruntime_static.py of mmdeploy or mmyolo, is not ok. 
for mmdeploy static.py, raise KeyError(f'Cannot get key by value "{value}" of {cls}')
KeyError: 'Cannot get key by value "mmyolo" of <enum \'Codebase\'>'

for mmyolo static.py, raise
  File "tools/deploy.py", line 130, in main
    device=args.device)
  File "/home/ubuntu/PycharmProjects/MMDeploy/mmdeploy/backend/sdk/export_info.py", line 407, in export2SDK
    pipeline_info = get_pipeline(deploy_cfg, model_cfg, work_dir, device)
  File "/home/ubuntu/PycharmProjects/MMDeploy/mmdeploy/backend/sdk/export_info.py", line 345, in get_pipeline
    preprocess = get_preprocess(deploy_cfg, model_cfg, device)
  File "/home/ubuntu/PycharmProjects/MMDeploy/mmdeploy/backend/sdk/export_info.py", line 219, in get_preprocess
    pipeline = task_processor.get_preprocess()
  File "/home/ubuntu/PycharmProjects/MMDeploy/mmdeploy/codebase/mmdet/deploy/object_detection.py", line 294, in get_preprocess
    model_cfg = process_model_config(self.model_cfg, [''], input_shape)
  File "/home/ubuntu/PycharmProjects/MMDeploy/mmdeploy/codebase/mmdet/deploy/object_detection.py", line 53, in process_model_config
    cfg.data.test.pipeline = replace_ImageToTensor(cfg.data.test.pipeline)
  File "/home/ubuntu/anaconda3/envs/openmm37clone/lib/python3.7/site-packages/mmcv/utils/config.py", line 48, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'data'

thanks.

**Comment by vansin** [comment]
please use 

mmengine
mmcv 2.x
mmdet 3.x
mmdeploy dev-1.x
