### ISSUE TITLE
loading testing image

### ISSUE THREAD

**Issue by yueyanpeng** [open-mmlab/mmyolo#357]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmyolo/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmyolo.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmyolo).

### 🐞 Describe the bug

HI there,
I tried inferencing from image ndarray today and noticed that "LoadImageFromArray" is not in the transform registry. However, it is included in inference detector.

### Environment

conda

**Comment by yueyanpeng** [comment]
With _Fix module unregistered error when MMYOLO calls inference_detector #9242_ 
Traceback (most recent call last):
  File "/home/ubuntu/mmyolo/demo/video_in_demo.py", line 388, in <module>
    main(args)
  File "/home/ubuntu/mmyolo/demo/video_in_demo.py", line 128, in main
    result = inference_detector(model, frame)
  File "/home/ubuntu/anaconda3/envs/mmyolo/lib/python3.8/site-packages/mmdet/apis/inference.py", line 149, in inference_detector
    data_ = test_pipeline(data_)
  File "/home/ubuntu/anaconda3/envs/mmyolo/lib/python3.8/site-packages/mmcv/transforms/base.py", line 11, in __call__
    return self.transform(results)
  File "/home/ubuntu/anaconda3/envs/mmyolo/lib/python3.8/site-packages/mmcv/transforms/wrappers.py", line 87, in transform
    results = t(results)  # type: ignore
  File "/home/ubuntu/anaconda3/envs/mmyolo/lib/python3.8/site-packages/mmcv/transforms/base.py", line 11, in __call__
    return self.transform(results)
  File "/home/ubuntu/anaconda3/envs/mmyolo/lib/python3.8/site-packages/mmdet/datasets/transforms/loading.py", line 389, in transform
    self._load_bboxes(results)
  File "/home/ubuntu/mmyolo/mmyolo/datasets/transforms/transforms.py", line 366, in _load_bboxes
    for instance in results['instances']:
KeyError: 'instances'

**Comment by hhaAndroid** [comment]
@yueyanpeng Please update the mmdet version, this problem was fixed in the previous version
