### ISSUE TITLE
Can't convert yolov5s model into onnx format with docker container.

### ISSUE THREAD

**Issue by thinktu2** [open-mmlab/mmyolo#451]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmyolo/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmyolo.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmyolo).

### 🐞 Describe the bug

I build a docker image to deploy model with `docker/Dockerfile_deployment` file in [tutorial](https://github.com/open-mmlab/mmyolo/blob/main/docs/en/deploy/yolov5_deployment.md#deploy-using-docker).
Then I create a container, `exec` it and run partial `script.sh` written in tutorial to convert yolov5s into onnx format.
```shell
export MMDEPLOY_DIR=/openmmlab/mmdeploy
export PATH_TO_CHECKPOINTS=/openmmlab/mmyolo/ckpt/yolov5s.pth
python3 ${MMDEPLOY_DIR}/tools/deploy.py \
>   configs/deploy/detection_onnxruntime_static.py \
>   configs/deploy/model/yolov5_s-static.py \
>   ${PATH_TO_CHECKPOINTS} \
>   demo/demo.jpg \
>   --work-dir work_dir_ort \
>   --device cuda:0
```
I get the following information, not the expected output mentioned in tutorial.
```shell
01/10 13:27:47 - mmengine - INFO - Start pipeline mmdeploy.apis.pytorch2onnx.torch2onnx in subprocess
01/10 13:27:47 - mmengine - WARNING - Failed to get codebase, got: 'Cannot get key by value "mmyolo" of <enum \'Codebase\'>'. Then export a new codebase in Codebase MMYOLO: mmyolo
NOTE! Installing ujson may make loading annotations faster.
01/10 13:27:48 - mmengine - WARNING - Import mmdeploy.codebase.mmyolo.deploy failedPlease check whether the module is the custom module.No module named 'mmdeploy.codebase.mmyolo'
01/10 13:27:48 - mmengine - WARNING - Import mmdeploy.codebase.mmyolo.deploy failedPlease check whether the module is the custom module.No module named 'mmdeploy.codebase.mmyolo'
01/10 13:27:48 - mmengine - WARNING - Failed to search registry with scope "mmyolo" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmyolo" is a correct scope, or whether the registry is initialized.
01/10 13:27:48 - mmengine - WARNING - The "mmyolo_tasks" registry in mmyolo did not set import location. Fallback to call `mmyolo.utils.register_all_modules` instead.
01/10 13:27:48 - mmengine - WARNING - Import mmdeploy.codebase.mmyolo.deploy failedPlease check whether the module is the custom module.No module named 'mmdeploy.codebase.mmyolo'
01/10 13:27:48 - mmengine - WARNING - Failed to search registry with scope "mmyolo" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmyolo" is a correct scope, or whether the registry is initialized.
01/10 13:27:48 - mmengine - WARNING - The "model" registry in mmyolo did not set import location. Fallback to call `mmyolo.utils.register_all_modules` instead.
01/10 13:27:48 - mmengine - WARNING - The "model" registry in mmdet did not set import location. Fallback to call `mmdet.utils.register_all_modules` instead.
01/10 13:27:48 - mmengine - WARNING - The "task util" registry in mmyolo did not set import location. Fallback to call `mmyolo.utils.register_all_modules` instead.
01/10 13:27:48 - mmengine - WARNING - The "task util" registry in mmdet did not set import location. Fallback to call `mmdet.utils.register_all_modules` instead.
Loads checkpoint by local backend from path: /openmmlab/mmyolo/ckpt/yolov5s.pth
Switch model to deploy modality.
01/10 13:27:49 - mmengine - WARNING - The "transform" registry in mmyolo did not set import location. Fallback to call `mmyolo.utils.register_all_modules` instead.
Process Process-2:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
TypeError: __init__() got an unexpected keyword argument 'file_client_args'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/conda/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/openmmlab/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/openmmlab/mmdeploy/mmdeploy/apis/pytorch2onnx.py", line 64, in torch2onnx
    data, model_inputs = task_processor.create_input(
  File "/openmmlab/mmdeploy/mmdeploy/codebase/mmdet/deploy/object_detection.py", line 204, in create_input
    test_pipeline = Compose(pipeline)
  File "/openmmlab/mmcv/mmcv/transforms/wrappers.py", line 65, in __init__
    transform = TRANSFORMS.build(transform)
  File "/opt/conda/lib/python3.8/site-packages/mmengine/registry/registry.py", line 521, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/opt/conda/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 135, in build_from_cfg
    raise type(e)(
TypeError: class `LoadImageFromFile` in mmcv/transforms/loading.py: __init__() got an unexpected keyword argument 'file_client_args'
01/10 13:27:50 - mmengine - ERROR - /openmmlab/mmdeploy/mmdeploy/apis/core/pipeline_manager.py - pop_mp_output - 80 - `mmdeploy.apis.pytorch2onnx.torch2onnx` with Call id: 0 failed. exit.
```

### Environment

I just build the environment with docker file. I run `python mmyolo/utils/collect_env.py` and I get the followings.
```shell
sys.platform: linux
Python: 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:10) [GCC 10.3.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0: NVIDIA GeForce RTX 3070 Ti
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.6, V11.6.124
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PyTorch: 1.12.0a0+bd13bc6
PyTorch compiling details: PyTorch built with:
  - GCC 9.4
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2019.0.5 Product Build 20190808 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.5.2 (Git Hash N/A)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 11.6
  - NVCC architecture flags: -gencode;arch=compute_52,code=sm_52;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_86,code=compute_86
  - CuDNN 8.4
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.6, CUDNN_VERSION=8.4.0, CXX_COMPILER=/usr/bin/c++, CXX_FLAGS=-fno-gnu-unique -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.12.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=ON, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF,

TorchVision: 0.13.0a0
OpenCV: 4.5.5
MMEngine: 0.4.0
MMCV: 2.0.0rc3
MMDetection: 3.0.0rc5
MMYOLO: 0.3.0+c682ae8
```

### Additional information

1. I modified the docker file. Because I can not clone `mmdeploy` repo and update submodule through `git` for some reason as you know. So I run clone and update command in the environment which can visit github, and then `COPY` mmdeploy to `/openmmlab/mmdeploy`. Specifically, I add `COPY mmdeploy/ /openmmlab/mmdeploy/` and remove `git clone https://github.com/open-mmlab/mmdeploy -b dev-1.x mmdeploy && git submodule update --init --recursive` in dockerfile.
2. I use `coco2017` dataset. This info is not helpful in deployment steps because I do not quantize model with partial dataset.
3. Maybe the cuda version result in this bug. I just use the `GPU 1` on physical machine in container, but the `GPU 0` need a higher cuda version than `11.6`.
```shell
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.60.11    Driver Version: 525.60.11    CUDA Version: 12.0     |
+-------------------------------+----------------------+----------------------+
GPU 0: NVIDIA GeForce RTX 4090
GPU 1: NVIDIA GeForce RTX 3070 Ti
```
I'm looking forward to your reply. Thanks for your patience.

**Comment by thinktu2** [comment]
I've solved this problem. It is caused by class `LoadImageFromFile` in `mmcv`. Edit `configs/deploy/model/yolov5_s-static.py` line `4`, drop the param `file_client_args=_base_.file_client_args`.
```python
_base_ = '../../yolov5/yolov5_s-v61_syncbn_8xb16-300e_coco.py'

test_pipeline = [
    # dict(type='LoadImageFromFile', file_client_args=_base_.file_client_args), # origin
    dict(type='LoadImageFromFile'), # edit
    # keep other lines...
]
```
Then I get the expected `end2end.onnx` in workdir.
I hope this conflict issue can be resolved in following releases.
