### ISSUE TITLE
[Bug]RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED 

### ISSUE THREAD

**Issue by tianleiSHI** [open-mmlab/mmyolo#472]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmyolo/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmyolo.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmyolo).

### 🐞 Describe the bug

```shell
python tools/train.py configs/custom_dataset/yolov5_s-v61_syncbn_fast_1xb32-100e_midogA.py 
```

```shell
Traceback (most recent call last):   
File "tools/train.py", line 116, in <module>     main()   
File "tools/train.py", line 112, in main     runner.train()   
File "/home/shitianlei/anaconda3/envs/PyTorch/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1678, in train     model = self.train_loop.run()  # type: ignore   
File "/home/shitianlei/anaconda3/envs/PyTorch/lib/python3.8/site-packages/mmengine/runner/loops.py", line 90, in run     self.run_epoch()   
File "/home/shitianlei/anaconda3/envs/PyTorch/lib/python3.8/site-packages/mmengine/runner/loops.py", line 106, in run_epoch     self.run_iter(idx, data_batch)   
File "/home/shitianlei/anaconda3/envs/PyTorch/lib/python3.8/site-packages/mmengine/runner/loops.py", line 122, in run_iter     outputs = self.runner.model.train_step(   
File "/home/shitianlei/anaconda3/envs/PyTorch/lib/python3.8/site-packages/mmengine/model/base_model/base_model.py", line 114, in train_step     losses = self._run_forward(data, mode='loss')  # type: ignore   
File "/home/shitianlei/anaconda3/envs/PyTorch/lib/python3.8/site-packages/mmengine/model/base_model/base_model.py", line 314, in _run_forward     results = self(**data, mode=mode)   
File "/home/shitianlei/anaconda3/envs/PyTorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl     return forward_call(*input, **kwargs)   
File "/home/shitianlei/anaconda3/envs/PyTorch/lib/python3.8/site-packages/mmdet/models/detectors/base.py", line 92, in forward     return self.loss(inputs, data_samples)   
File "/home/shitianlei/anaconda3/envs/PyTorch/lib/python3.8/site-packages/mmdet/models/detectors/single_stage.py", line 77, in loss     x = self.extract_feat(batch_inputs)   
File "/home/shitianlei/anaconda3/envs/PyTorch/lib/python3.8/site-packages/mmdet/models/detectors/single_stage.py", line 143, in extract_feat     x = self.backbone(batch_inputs)   File "/home/shitianlei/anaconda3/envs/PyTorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl     return forward_call(*input, **kwargs)   
File "/data1/shitianlei/openmmlab/mmyolo/mmyolo/models/backbones/base_backbone.py", line 221, in forward     x = layer(x)   File "/home/shitianlei/anaconda3/envs/PyTorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl     return forward_call(*input, **kwargs)   
File "/home/shitianlei/anaconda3/envs/PyTorch/lib/python3.8/site-packages/mmcv/cnn/bricks/conv_module.py", line 207, in forward     x = self.conv(x)   
File "/home/shitianlei/anaconda3/envs/PyTorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl     return forward_call(*input, **kwargs)   
File "/home/shitianlei/anaconda3/envs/PyTorch/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 463, in forward     return self._conv_forward(input, self.weight, self.bias)   
File "/home/shitianlei/anaconda3/envs/PyTorch/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward     return F.conv2d(input, weight, bias, self.stride, 
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED 

### Environment

DA available: True
numpy_random_seed: 2147483648
GPU 0,1,2,3: NVIDIA GeForce RTX 3090
CUDA_HOME: /home/shitianlei/anaconda3/envs/PyTorch
NVCC: Cuda compilation tools, release 11.6, V11.6.124
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PyTorch: 1.13.0
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.6
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.3.2  (built against CUDA 11.5)
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.6, CUDNN_VERSION=8.3.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF,

TorchVision: 0.2.1
OpenCV: 4.6.0
MMEngine: 0.4.0
MMCV: 2.0.0rc3
MMDetection: 3.0.0rc5
MMYOLO: 0.3.0+b0cf073

### Additional information

I also try to set cudnn_benchmark=False in config file or change torch version, but it doesn't work for me https://github.com/open-mmlab/mmdetection/issues/7962

```python

_base_ = '../yolov5/yolov5_s-v61_syncbn_fast_8xb16-300e_coco.py'

max_epochs = 100
data_root = 'MIDOG/trainA/'
# data_root = '/root/workspace/mmyolo/data/cat/'  # Docker

work_dir = 'MIDOG/work_dirs/yolov5_s-v61_syncbn_fast_1xb32-100e_midogA'

load_from = 'https://download.openmmlab.com/mmyolo/v0/yolov5/yolov5_s-v61_syncbn_fast_8xb16-300e_coco/yolov5_s-v61_syncbn_fast_8xb16-300e_coco_20220918_084700-86e02187.pth'  # noqa

train_batch_size_per_gpu = 8
train_num_workers = 4

save_epoch_intervals = 2

# base_lr_default * (your_bs / default_bs)
base_lr = _base_.base_lr / 4

anchors = [[[4, 40], [62, 62], [207, 210]],
           [[222, 423], [331, 391], [369, 458]],
           [[574, 330], [607, 624], [588, 861]]]

class_name = ('mitotic figure','not mitotic figure', )
num_classes = len(class_name)
metainfo = dict(classes=class_name, palette=[(220, 20, 60)])

train_cfg = dict(
    max_epochs=max_epochs, val_begin=20, val_interval=save_epoch_intervals)

model = dict(
    bbox_head=dict(
        head_module=dict(num_classes=num_classes),
        prior_generator=dict(base_sizes=anchors),
        loss_cls=dict(loss_weight=0.5 *
                      (num_classes / 80 * 3 / _base_.num_det_layers))))

train_dataloader = dict(
    batch_size=train_batch_size_per_gpu,
    num_workers=train_num_workers,
    dataset=dict(
        _delete_=True,
        type='RepeatDataset',
        times=5,
        dataset=dict(
            type=_base_.dataset_type,
            data_root=data_root,
            metainfo=metainfo,
            ann_file='annotations/train_patch.json',
            data_prefix=dict(img='images/'),
            filter_cfg=dict(filter_empty_gt=False, min_size=32),
            pipeline=_base_.train_pipeline)))

val_dataloader = dict(
    dataset=dict(
        metainfo=metainfo,
        data_root=data_root,
        ann_file='annotations/val_patch.json',
        data_prefix=dict(img='images/')))

test_dataloader = val_dataloader

val_evaluator = dict(ann_file=data_root + 'annotations/val_patch.json')
test_evaluator = val_evaluator

optim_wrapper = dict(optimizer=dict(lr=base_lr))

default_hooks = dict(
    checkpoint=dict(
        type='CheckpointHook',
        interval=save_epoch_intervals,
        max_keep_ckpts=5,
        save_best='auto'),
    param_scheduler=dict(max_epochs=max_epochs),
    logger=dict(type='LoggerHook', interval=10))

visualizer = dict(vis_backends=[dict(type='LocalVisBackend'),
                                dict(type='WandbVisBackend')])
```

**Comment by tianleiSHI** [comment]
The bug was fixed when I added the following to the `train.py` script. There may be something wrong with my environment configuration.
```python
import torch
torch.backends.cuda.matmul.allow_tf32 = False
torch.backends.cudnn.benchmark = True
torch.backends.cudnn.deterministic = False
torch.backends.cudnn.allow_tf32 = True
torch.cuda.synchronize
```
