### ISSUE TITLE
Mosaic导致报错

### ISSUE THREAD

**Issue by wangwuwu** [open-mmlab/mmyolo#527]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmyolo/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmyolo.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmyolo).

### 🐞 Describe the bug

当数据集中图片尺寸不一且开启Mosaic的cache功能时，开始的几张图片会在yolov5_collate函数中cat出错

### Environment

mmyolo-v0.4.0

**Comment by wangwuwu** [comment]
。

**Comment by rhett-ye** [comment]
> ### Prerequisite
> * [x]  I have searched [the existing and past issues](https://github.com/open-mmlab/mmyolo/issues) but cannot get the expected help.
> * [x]  I have read the [FAQ documentation](https://mmyolo.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
> * [x]  The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmyolo).
> 
> ### 🐞 Describe the bug
> 当数据集中图片尺寸不一且开启Mosaic的cache功能时，开始的几张图片会在yolov5_collate函数中cat出错
> 
> ### Environment
> mmyolo-v0.4.0
> 
> ### Additional information
> _No response_

I have same problem, have you solved it?

**Comment by wangwuwu** [comment]
> 

前四张图片直接resize并LetterResize到输入尺寸就可以了，

if len(self.results_cache) <= 4:
    results=self.keepratio_resize(results)
    results=self.letteresize(results)
    return results

**Comment by rhett-ye** [comment]
> > 
> 
> 前四张图片直接resize并LetterResize到输入尺寸就可以了，
> 
> if len(self.results_cache) <= 4: results=self.keepratio_resize(results) results=self.letteresize(results) return results

I modified **mix_img_transforms.py** according to your code, and get error as follow:

Original Traceback (most recent call last):
  File "/opt/conda/envs/mmyolo/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/envs/mmyolo/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/envs/mmyolo/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/envs/mmyolo/lib/python3.8/site-packages/mmengine/dataset/base_dataset.py", line 408, in __getitem__
    data = self.prepare_data(idx)
  File "/root/project/yemiaolong/mmyolo-0.6.0/mmyolo/datasets/yolov5_coco.py", line 53, in prepare_data
    return self.pipeline(data_info)
  File "/opt/conda/envs/mmyolo/lib/python3.8/site-packages/mmengine/dataset/base_dataset.py", line 58, in __call__
    data = t(data)
  File "/opt/conda/envs/mmyolo/lib/python3.8/site-packages/mmcv/transforms/base.py", line 12, in __call__
    return self.transform(results)
  File "/opt/conda/envs/mmyolo/lib/python3.8/site-packages/mmdet/structures/bbox/box_type.py", line 267, in wrapper
    return func(self, results)
  File "/root/project/yemiaolong/mmyolo-0.6.0/mmyolo/datasets/transforms/mix_img_transforms.py", line 168, in transform
    _results.pop('dataset')
KeyError: 'dataset'
