### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by BainOuO** [open-mmlab/mmyolo#609]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmyolo/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmyolo.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmyolo).

### 🐞 Describe the bug

Traceback (most recent call last):
  File "tools/train.py", line 116, in <module>
    main()
  File "tools/train.py", line 112, in main
    runner.train()
  File "/home/zckj/miniconda3/envs/bain/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1686, in train
    model = self.train_loop.run()  # type: ignore
  File "/home/zckj/miniconda3/envs/bain/lib/python3.8/site-packages/mmengine/runner/loops.py", line 90, in run
    self.run_epoch()
  File "/home/zckj/miniconda3/envs/bain/lib/python3.8/site-packages/mmengine/runner/loops.py", line 106, in run_epoch
    self.run_iter(idx, data_batch)
  File "/home/zckj/miniconda3/envs/bain/lib/python3.8/site-packages/mmengine/runner/loops.py", line 122, in run_iter
    outputs = self.runner.model.train_step(
  File "/home/zckj/miniconda3/envs/bain/lib/python3.8/site-packages/mmengine/model/base_model/base_model.py", line 114, in train_step
    losses = self._run_forward(data, mode='loss')  # type: ignore
  File "/home/zckj/miniconda3/envs/bain/lib/python3.8/site-packages/mmengine/model/base_model/base_model.py", line 326, in _run_forward
    results = self(**data, mode=mode)
  File "/home/zckj/miniconda3/envs/bain/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/zckj/miniconda3/envs/bain/lib/python3.8/site-packages/mmdet/models/detectors/base.py", line 92, in forward
    return self.loss(inputs, data_samples)
  File "/home/zckj/miniconda3/envs/bain/lib/python3.8/site-packages/mmdet/models/detectors/single_stage.py", line 78, in loss
    losses = self.bbox_head.loss(x, batch_data_samples)
  File "/home/zckj/bby/mmyolo/mmyolo/models/dense_heads/yolov5_head.py", line 461, in loss
    outs = self(x)
  File "/home/zckj/miniconda3/envs/bain/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/zckj/bby/mmyolo/mmyolo/models/dense_heads/yolov5_head.py", line 269, in forward
    return self.head_module(x)
  File "/home/zckj/miniconda3/envs/bain/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/zckj/bby/mmyolo/mmyolo/models/dense_heads/yolov5_head.py", line 112, in forward
    assert len(x) == self.num_levels
AssertionError

### Environment

Exchange the backbone network convnext for yolov5s

-------------------------------------------------------------------------------------------

custom_imports = dict(imports=['mmcls.models'], allow_failed_imports=False)
checkpoint_file = 'https://download.openmmlab.com/mmclassification/v0/convnext/downstream/convnext-tiny_3rdparty_32xb128-noema_in1k_20220301-795e9634.pth'  # noqa
# widen_factor = 1.0
channels = [96, 192, 384, 768]

# fast means faster training speed,
# but less flexibility for multitasking
model = dict(
    type='YOLODetector',
    data_preprocessor=dict(
        type='YOLOv5DetDataPreprocessor',
        mean=[0., 0., 0.],
        std=[255., 255., 255.],
        bgr_to_rgb=True),
    backbone=dict(
        _delete_=True,
        type='mmcls.ConvNeXt',
        arch='tiny',
        out_indices=[0, 1, 2, 3],
        drop_path_rate=0.4,
        layer_scale_init_value=1.0,
        gap_before_final_norm=False,
        init_cfg=dict(
            type='Pretrained', checkpoint=checkpoint_file,
            prefix='backbone.')),
    neck=dict(
        type='YOLOv5PAFPN',
        deepen_factor=deepen_factor,
        widen_factor=widen_factor,
        in_channels=channels,
        out_channels=channels,
        num_csp_blocks=3,
        norm_cfg=dict(type='BN', momentum=0.03, eps=0.001),
        act_cfg=dict(type='SiLU', inplace=True)),
    bbox_head=dict(
        type='YOLOv5Head',
        head_module=dict(
            type='YOLOv5HeadModule',
            num_classes=num_classes,
            in_channels=channels,
            widen_factor=widen_factor,
            featmap_strides=strides,
            num_base_priors=3),
        prior_generator=dict(
            type='mmdet.YOLOAnchorGenerator',
            base_sizes=anchors,
            strides=strides),
        # scaled based on number of detection layers
        loss_cls=dict(
            type='mmdet.CrossEntropyLoss',
            use_sigmoid=True,
            reduction='mean',
            loss_weight=0.5 * (num_classes / 80 * 3 / num_det_layers)),
        loss_bbox=dict(
            type='IoULoss',
            iou_mode='ciou',
            bbox_format='xywh',
            eps=1e-7,
            reduction='mean',
            loss_weight=0.05 * (3 / num_det_layers),
            return_iou=True),
        loss_obj=dict(
            type='mmdet.CrossEntropyLoss',
            use_sigmoid=True,
            reduction='mean',
            loss_weight=1.0 * ((img_scale[0] / 640)**2 * 3 / num_det_layers)),
        prior_match_thr=4.,
        obj_level_weights=[4., 1., 0.4]),
    test_cfg=dict(
        multi_label=True,
        nms_pre=30000,
        score_thr=0.001,
        nms=dict(type='nms', iou_threshold=0.65),
        max_per_img=300))

**Comment by RangeKing** [comment]
Hi, @BainOuO. The default `num_levels` of YOLOv5s backbone output is 3. You need to modify the `out_indices` to (1, 2, 3) and the `channels` to [192, 384, 768].
Here's the example config, https://mmyolo.readthedocs.io/en/dev/recommended_topics/replace_backbone.html#use-backbone-network-implemented-in-mmclassification.

**Comment by BainOuO** [comment]
> Hi, @BainOuO. The default `num_levels` of YOLOv5s backbone output is 3. You need to modify the `out_indices` to (1, 2, 3) and the `channels` to [192, 384, 768]. Here's the example config, https://mmyolo.readthedocs.io/en/dev/recommended_topics/replace_backbone.html#use-backbone-network-implemented-in-mmclassification.

shuan Q~
