### ISSUE TITLE
yolov5s replacement siou error

### ISSUE THREAD

**Issue by BainOuO** [open-mmlab/mmyolo#642]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmyolo/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmyolo.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmyolo).

### 🐞 Describe the bug

Traceback (most recent call last):
  File "tools/train.py", line 115, in <module>
    main()
  File "tools/train.py", line 111, in main
    runner.train()
  File "/home/zckj/miniconda3/envs/mmyolo_0_5/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1686, in train
    model = self.train_loop.run()  # type: ignore
  File "/home/zckj/miniconda3/envs/mmyolo_0_5/lib/python3.8/site-packages/mmengine/runner/loops.py", line 90, in run
    self.run_epoch()
  File "/home/zckj/miniconda3/envs/mmyolo_0_5/lib/python3.8/site-packages/mmengine/runner/loops.py", line 106, in run_epoch
    self.run_iter(idx, data_batch)
  File "/home/zckj/miniconda3/envs/mmyolo_0_5/lib/python3.8/site-packages/mmengine/runner/loops.py", line 122, in run_iter
    outputs = self.runner.model.train_step(
  File "/home/zckj/miniconda3/envs/mmyolo_0_5/lib/python3.8/site-packages/mmengine/model/base_model/base_model.py", line 114, in train_step
    losses = self._run_forward(data, mode='loss')  # type: ignore
  File "/home/zckj/miniconda3/envs/mmyolo_0_5/lib/python3.8/site-packages/mmengine/model/base_model/base_model.py", line 326, in _run_forward
    results = self(**data, mode=mode)
  File "/home/zckj/miniconda3/envs/mmyolo_0_5/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zckj/miniconda3/envs/mmyolo_0_5/lib/python3.8/site-packages/mmdet/models/detectors/base.py", line 92, in forward
    return self.loss(inputs, data_samples)
  File "/home/zckj/miniconda3/envs/mmyolo_0_5/lib/python3.8/site-packages/mmdet/models/detectors/single_stage.py", line 78, in loss
    losses = self.bbox_head.loss(x, batch_data_samples)
  File "/home/zckj/bby/mmyolo_0_5/mmyolo/mmyolo/models/dense_heads/yolov5_head.py", line 459, in loss
    losses = super().loss(x, batch_data_samples)
  File "/home/zckj/miniconda3/envs/mmyolo_0_5/lib/python3.8/site-packages/mmdet/models/dense_heads/base_dense_head.py", line 123, in loss
    losses = self.loss_by_feat(*loss_inputs)
  File "/home/zckj/bby/mmyolo_0_5/mmyolo/mmyolo/models/dense_heads/yolov5_head.py", line 612, in loss_by_feat
    loss_box_i, iou = self.loss_bbox(decoded_bbox_pred, bboxes_targets)
  File "/home/zckj/miniconda3/envs/mmyolo_0_5/lib/python3.8/site-packages/torch/_tensor.py", line 642, in __iter__
    raise TypeError('iteration over a 0-d tensor')
TypeError: iteration over a 0-d tensor

### Environment

Use the format of yolov6

loss_bbox=dict(
            type='IoULoss',
            iou_mode='siou',
            bbox_format='xyxy',
            reduction='mean',
            loss_weight=2.5,
            return_iou=False)

**Comment by Nioolek** [comment]
Set `return_iou=True`, the bug will disappear. YOLOv5 use iou as the label of objectness branch, so you should set `return_iou=True`
