### ISSUE TITLE
Error: Yolov5 with Yolov8Head

### ISSUE THREAD

**Issue by nakuda1** [open-mmlab/mmyolo#668]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmyolo/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmyolo.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmyolo).

### 🐞 Describe the bug

When I changed the yolov5head to yolov8head,  it had an error. I do not how to config and solve.

```python
===============================================================
code:
model = dict(
    backbone=dict(
        _delete_=True,  # 将 _base_ 中关于 backbone 的字段删除
        type='mmcls.TIMMBackbone',  # 使用 mmcls 中的 timm 主干网络
        model_name='mobilevitv2_050',  # 使用 TIMM 中的 mobilevitv2_050
        features_only=True,
        pretrained=True,
        out_indices=(2, 3, 4)),
    neck=dict(
        _delete_=True,
        type='PPYOLOECSPPAFPN',
        widen_factor=widen_factor,
        in_channels=channels,  # 注意：mobilevitv2_050 输出的3个通道是 [128, 192, 256]，和原先的 yolov5-s neck 不匹配，需要更改
        out_channels=channels),
    bbox_head=dict(
        _delete_=True,
        type='YOLOv8Head',
        head_module=dict(
            type='YOLOv8HeadModule',
            featmap_strides=strides, # 3.16/2022加入
            num_classes= 2,#3.16/2022加入
            in_channels=channels,  # head 部分输入通道也要做相应更改
            widen_factor=widen_factor))
)
------------------------------------------------------------------
```
error:
Traceback (most recent call last):
  File "tools/train.py", line 115, in <module>
    main()
  File "tools/train.py", line 111, in main
    runner.train()
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1686, in train
    model = self.train_loop.run()  # type: ignore
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/runner/loops.py", line 90, in run
    self.run_epoch()
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/runner/loops.py", line 106, in run_epoch
    self.run_iter(idx, data_batch)
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/runner/loops.py", line 122, in run_iter
    outputs = self.runner.model.train_step(
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/model/base_model/base_model.py", line 114, in train_step
    losses = self._run_forward(data, mode='loss')  # type: ignore
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/model/base_model/base_model.py", line 326, in _run_forward
    results = self(**data, mode=mode)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/mmdet/models/detectors/base.py", line 92, in forward
    return self.loss(inputs, data_samples)
  File "/root/miniconda3/lib/python3.8/site-packages/mmdet/models/detectors/single_stage.py", line 78, in loss
    losses = self.bbox_head.loss(x, batch_data_samples)
  File "/root/Swin-Transformer-Object-Detection/mmyolo/mmyolo/models/dense_heads/yolov5_head.py", line 459, in loss
    losses = super().loss(x, batch_data_samples)
  File "/root/miniconda3/lib/python3.8/site-packages/mmdet/models/dense_heads/base_dense_head.py", line 123, in loss
    losses = self.loss_by_feat(*loss_inputs)
  File "/root/Swin-Transformer-Object-Detection/mmyolo/mmyolo/models/dense_heads/yolov8_head.py", line 297, in loss_by_feat
    if current_featmap_sizes != self.featmap_sizes_train:
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1177, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'YOLOv8Head' object has no attribute 'featmap_sizes_train'

### Environment

normal env

**Comment by xin-li-67** [comment]
Hi, have you checked with this [document](https://github.com/open-mmlab/mmyolo/blob/main/docs/zh_cn/common_usage/module_combination.md#3-yolov5-headmodule-%E6%9B%BF%E6%8D%A2)?

**Comment by nakuda1** [comment]
> Hi, have you checked with this [document](https://github.com/open-mmlab/mmyolo/blob/main/docs/zh_cn/common_usage/module_combination.md#3-yolov5-headmodule-%E6%9B%BF%E6%8D%A2)?

Yes, I did. You can see my code that is followed the tutorial. But It still has bug.

**Comment by xin-li-67** [comment]
> > Hi, have you checked with this [document](https://github.com/open-mmlab/mmyolo/blob/main/docs/zh_cn/common_usage/module_combination.md#3-yolov5-headmodule-%E6%9B%BF%E6%8D%A2)?
> 
> Yes, I did. You can see my code that is followed the tutorial. But It still has bug.

I tried on my local device with the latest dev branch but I didn't get the same error. My customized model config is as follows:
```python
model = dict(
    backbone=dict(
        _delete_=True,
        type='mmcls.TIMMBackbone',
        model_name='mobilevitv2_050',
        features_only=True,
        pretrained=True,
        out_indices=(2, 3, 4)
    ),
    neck=dict(
        _delete_=True,
        type='PPYOLOECSPPAFPN',
        widen_factor=widen_factor,
        in_channels=channels,
        out_channels=channels
    ),
    bbox_head=dict(
        _delete_=True,
        type='YOLOv8Head',
        head_module=dict(
            type='YOLOv8HeadModule',
            num_classes=2,
            in_channels=channels,
            widen_factor=widen_factor)
    )
)
```

**Comment by hhaAndroid** [comment]
@nakuda1 Thanks for your feedback, we'll give it a try

**Comment by Nioolek** [comment]
Hello, thank you for your feedback. You need to add `train_cfg` in config to help `YOLOv8Head` to init `featmap_sizes_train`.
You can see link below for more detail.
https://github.com/open-mmlab/mmyolo/blob/d06de6d36fd05086641921aef7054f72176a0f68/mmyolo/models/dense_heads/yolov8_head.py#L250
