### ISSUE TITLE
自定义旋转目标检测数据集的问题

### ISSUE THREAD

**Issue by KimWu1994** [open-mmlab/mmyolo#698]
### Model/Dataset description

Hello, I have converted the required dataset format to the DOTA dataset format for detection by myself, and it can also run well in mmrotate.

I define my dataset in mmyolo as follows:

```
class Instrument(DOTADataset):
    """SAR ship dataset for detection (Support RSSDD and HRSID)."""
    CLASSES = ('1', )
    PALETTE = [
        (0, 255, 0),
    ]


@DATASETS.register_module()
class YOLOv5Instrument(BatchShapePolicyDataset, Instrument):
    """Dataset for YOLOv5 DOTA Dataset.

    We only add `BatchShapePolicy` function compared with DOTADataset. See
    `mmyolo/datasets/utils.py#BatchShapePolicy` for details
    """
    CLASS = ('1', )
    def __init__(self, *args, **kwargs):
        if not MMROTATE_AVAILABLE:
            raise ImportError(
                'Please run "mim install -r requirements/mmrotate.txt" '
                'to install mmrotate first for rotated detection.')

        super().__init__(*args, **kwargs)
```

The bug is:

```
File "/home/jinlin_wu/anaconda3/envs/mmyolo/lib/python3.7/site-packages/mmrotate/datasets/dota.py", line 101, in load_data_list
    instance['bbox_label'] = cls_map[cls_name]
KeyError: '1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jinlin_wu/anaconda3/envs/mmyolo/lib/python3.7/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/home/jinlin_wu/anaconda3/envs/mmyolo/lib/python3.7/site-packages/mmengine/runner/loops.py", line 44, in __init__
    super().__init__(runner, dataloader)
  File "/home/jinlin_wu/anaconda3/envs/mmyolo/lib/python3.7/site-packages/mmengine/runner/base_loop.py", line 27, in __init__
    dataloader, seed=runner.seed, diff_rank_seed=diff_rank_seed)
  File "/home/jinlin_wu/anaconda3/envs/mmyolo/lib/python3.7/site-packages/mmengine/runner/runner.py", line 1341, in build_dataloader
    dataset = DATASETS.build(dataset_cfg)
  File "/home/jinlin_wu/anaconda3/envs/mmyolo/lib/python3.7/site-packages/mmengine/registry/registry.py", line 548, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/jinlin_wu/anaconda3/envs/mmyolo/lib/python3.7/site-packages/mmengine/registry/build_functions.py", line 136, in build_from_cfg
    f'class `{obj_cls.__name__}` in '  # type: ignore
KeyError: "class `YOLOv5Instrument` in mmyolo/datasets/yolov5_instrument.py: '1'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 115, in <module>
    main()
  File "tools/train.py", line 111, in main
    runner.train()
  File "/home/jinlin_wu/anaconda3/envs/mmyolo/lib/python3.7/site-packages/mmengine/runner/runner.py", line 1668, in train
    self._train_loop)  # type: ignore
  File "/home/jinlin_wu/anaconda3/envs/mmyolo/lib/python3.7/site-packages/mmengine/runner/runner.py", line 1462, in build_train_loop
    runner=self, dataloader=self._train_dataloader))
  File "/home/jinlin_wu/anaconda3/envs/mmyolo/lib/python3.7/site-packages/mmengine/registry/registry.py", line 548, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/jinlin_wu/anaconda3/envs/mmyolo/lib/python3.7/site-packages/mmengine/registry/build_functions.py", line 136, in build_from_cfg
    f'class `{obj_cls.__name__}` in '  # type: ignore
KeyError: 'class `EpochBasedTrainLoop` in mmengine/runner/loops.py: "class `YOLOv5Instrument` in mmyolo/datasets/yolov5_instrument.py: \'1\'"'
```

How to fix it?

### Open source status

- [ ] The model implementation is available
- [ ] The model weights are available.

**Comment by hhaAndroid** [comment]
@KimWu1994 You don't need to customize the data class. please refer to https://mmyolo.readthedocs.io/zh_CN/dev/get_started/15_minutes_object_detection.html#id3
