### ISSUE TITLE
15 Minute tutorial only works on yolov5

### ISSUE THREAD

**Issue by tendermonster** [open-mmlab/mmyolo#750]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmyolo/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmyolo.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmyolo).

### 🐞 Describe the bug

When i try to use either yolov7 or yolov7 it is not possible to train using given configurations on cat dataset

for yolov7 i get mAP of 0

for yolov8 i get fallowing error that i have no idea how to debug

Traceback (most recent call last):
  File "tools/train.py", line 115, in <module>
    main()
  File "tools/train.py", line 111, in main
    runner.train()
  File "/home/tinker/miniconda3/envs/mmyolo/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1689, in train
    self.call_hook('before_run')
  File "/home/tinker/miniconda3/envs/mmyolo/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1768, in call_hook
    getattr(hook, fn_name)(self, **kwargs)
  File "/home/tinker/miniconda3/envs/mmyolo/lib/python3.8/site-packages/mmengine/hooks/ema_hook.py", line 74, in before_run
    self.ema_model = MODELS.build(
  File "/home/tinker/miniconda3/envs/mmyolo/lib/python3.8/site-packages/mmengine/registry/registry.py", line 545, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/tinker/miniconda3/envs/mmyolo/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 241, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/tinker/miniconda3/envs/mmyolo/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 100, in build_from_cfg
    raise KeyError(
KeyError: 'ExpMomentumlast_stage_out_channelsEMA is not in the model registry. Please check whether the value of `ExpMomentumlast_stage_out_channelsEMA` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'

No code was modified

### Environment

sys.platform: linux
Python: 3.8.16 (default, Mar  2 2023, 03:21:46) [GCC 11.2.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0: NVIDIA GeForce RTX 3060
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.7, V11.7.99
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PyTorch: 2.0.0+cu117
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.7.3 (Git Hash 6dbeffbae1f23cbbeae17adb7b5b13f1f37c080e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.7
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.5
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.0.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.15.1+cu117
OpenCV: 4.7.0
MMEngine: 0.7.2
MMCV: 2.0.0
MMDetection: 3.0.0
MMYOLO: 0.5.0+dc85144

### Additional information

1. no modifications
2. cat dataset
3. maybe a version mismatch ?

**Comment by hhaAndroid** [comment]
@tendermonster You can directly run the yolov7 cat configuration we provided

**Comment by tendermonster** [comment]
@hhaAndroid One moment 

It does not matter for how long the model is trained. There is no convergence. It seems to me that the models' architecture is wrong or something. 

$ python tools/train.py configs/yolov7/yolov7_tiny_fast_1xb12-40e_cat.py

 You are using `YOLOv5Head` with num_classes == 1. The loss_cls will be 0. This is a normal phenomenon.
04/25 10:34:23 - mmengine - INFO - Distributed training is not used, all SyncBatchNorm (SyncBN) layers in the model will be automatically reverted to BatchNormXd layers if they are used.
04/25 10:34:23 - mmengine - INFO - Hooks will be executed in the following order:
before_run:
(VERY_HIGH   ) RuntimeInfoHook                    
(49          ) EMAHook                            
(BELOW_NORMAL) LoggerHook                         

after_load_checkpoint:
(49          ) EMAHook                            

before_train:
(9           ) YOLOv5ParamSchedulerHook           
(VERY_HIGH   ) RuntimeInfoHook                    
(49          ) EMAHook                            
(NORMAL      ) IterTimerHook                      
(VERY_LOW    ) CheckpointHook                     

before_train_epoch:
(VERY_HIGH   ) RuntimeInfoHook                    
(NORMAL      ) IterTimerHook                      
(NORMAL      ) DistSamplerSeedHook                

before_train_iter:
(9           ) YOLOv5ParamSchedulerHook           
(VERY_HIGH   ) RuntimeInfoHook                    
(NORMAL      ) IterTimerHook                      

after_train_iter:
(9           ) YOLOv5ParamSchedulerHook           
(VERY_HIGH   ) RuntimeInfoHook                    
(49          ) EMAHook                            
(NORMAL      ) IterTimerHook                      
(BELOW_NORMAL) LoggerHook                         
(VERY_LOW    ) CheckpointHook                     

after_train_epoch:
(9           ) YOLOv5ParamSchedulerHook           
(NORMAL      ) IterTimerHook                      
(VERY_LOW    ) CheckpointHook                     

before_val_epoch:
(49          ) EMAHook                            
(NORMAL      ) IterTimerHook                      

before_val_iter:
(NORMAL      ) IterTimerHook                      

after_val_iter:
(NORMAL      ) IterTimerHook                      
(NORMAL      ) DetVisualizationHook               
(BELOW_NORMAL) LoggerHook                         

after_val_epoch:
(9           ) YOLOv5ParamSchedulerHook           
(VERY_HIGH   ) RuntimeInfoHook                    
(49          ) EMAHook                            
(NORMAL      ) IterTimerHook                      
(BELOW_NORMAL) LoggerHook                         
(VERY_LOW    ) CheckpointHook                     

before_save_checkpoint:
(49          ) EMAHook                            

after_train:
(VERY_LOW    ) CheckpointHook                     

before_test_epoch:
(49          ) EMAHook                            
(NORMAL      ) IterTimerHook                      

before_test_iter:
(NORMAL      ) IterTimerHook                      

after_test_iter:
(NORMAL      ) IterTimerHook                      
(NORMAL      ) DetVisualizationHook               
(BELOW_NORMAL) LoggerHook                         

after_test_epoch:
(VERY_HIGH   ) RuntimeInfoHook                    
(49          ) EMAHook                            
(NORMAL      ) IterTimerHook                      
(BELOW_NORMAL) LoggerHook                         

after_run:
(BELOW_NORMAL) LoggerHook                         

loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
04/25 10:34:26 - mmengine - INFO - Scaled weight_decay to 0.00046875
04/25 10:34:26 - mmengine - INFO - Optimizer groups: 58 .bias, 58 conv.weight, 61 other
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
Loads checkpoint by http backend from path: https://download.openmmlab.com/mmyolo/v0/yolov7/yolov7_tiny_syncbn_fast_8x16b-300e_coco/yolov7_tiny_syncbn_fast_8x16b-300e_coco_20221126_102719-0ee5bbdf.pth
The model and loaded state dict do not match exactly

size mismatch for bbox_head.head_module.convs_pred.0.1.weight: copying a param with shape torch.Size([255, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([18, 128, 1, 1]).
size mismatch for bbox_head.head_module.convs_pred.0.1.bias: copying a param with shape torch.Size([255]) from checkpoint, the shape in current model is torch.Size([18]).
size mismatch for bbox_head.head_module.convs_pred.0.2.implicit: copying a param with shape torch.Size([1, 255, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 18, 1, 1]).
size mismatch for bbox_head.head_module.convs_pred.1.1.weight: copying a param with shape torch.Size([255, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([18, 256, 1, 1]).
size mismatch for bbox_head.head_module.convs_pred.1.1.bias: copying a param with shape torch.Size([255]) from checkpoint, the shape in current model is torch.Size([18]).
size mismatch for bbox_head.head_module.convs_pred.1.2.implicit: copying a param with shape torch.Size([1, 255, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 18, 1, 1]).
size mismatch for bbox_head.head_module.convs_pred.2.1.weight: copying a param with shape torch.Size([255, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([18, 512, 1, 1]).
size mismatch for bbox_head.head_module.convs_pred.2.1.bias: copying a param with shape torch.Size([255]) from checkpoint, the shape in current model is torch.Size([18]).
size mismatch for bbox_head.head_module.convs_pred.2.2.implicit: copying a param with shape torch.Size([1, 255, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 18, 1, 1]).
The model and loaded state dict do not match exactly

size mismatch for bbox_head.head_module.convs_pred.0.1.weight: copying a param with shape torch.Size([255, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([18, 128, 1, 1]).
size mismatch for bbox_head.head_module.convs_pred.0.1.bias: copying a param with shape torch.Size([255]) from checkpoint, the shape in current model is torch.Size([18]).
size mismatch for bbox_head.head_module.convs_pred.0.2.implicit: copying a param with shape torch.Size([1, 255, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 18, 1, 1]).
size mismatch for bbox_head.head_module.convs_pred.1.1.weight: copying a param with shape torch.Size([255, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([18, 256, 1, 1]).
size mismatch for bbox_head.head_module.convs_pred.1.1.bias: copying a param with shape torch.Size([255]) from checkpoint, the shape in current model is torch.Size([18]).
size mismatch for bbox_head.head_module.convs_pred.1.2.implicit: copying a param with shape torch.Size([1, 255, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 18, 1, 1]).
size mismatch for bbox_head.head_module.convs_pred.2.1.weight: copying a param with shape torch.Size([255, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([18, 512, 1, 1]).
size mismatch for bbox_head.head_module.convs_pred.2.1.bias: copying a param with shape torch.Size([255]) from checkpoint, the shape in current model is torch.Size([18]).
size mismatch for bbox_head.head_module.convs_pred.2.2.implicit: copying a param with shape torch.Size([1, 255, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 18, 1, 1]).
04/25 10:34:30 - mmengine - INFO - Load checkpoint from https://download.openmmlab.com/mmyolo/v0/yolov7/yolov7_tiny_syncbn_fast_8x16b-300e_coco/yolov7_tiny_syncbn_fast_8x16b-300e_coco_20221126_102719-0ee5bbdf.pth
04/25 10:34:30 - mmengine - WARNING - "FileClient" will be deprecated in future. Please use io functions in https://mmengine.readthedocs.io/en/latest/api/fileio.html#file-io
04/25 10:34:30 - mmengine - WARNING - "HardDiskBackend" is the alias of "LocalBackend" and the former will be deprecated in future.
04/25 10:34:30 - mmengine - INFO - Checkpoints will be saved to /home/tinker/code/git/ai_projects/mmyolo/work_dirs/yolov7_tiny_fast_1xb12-40e_cat.
04/25 10:34:49 - mmengine - INFO - Epoch(train)  [1][ 5/10]  lr: 1.3333e-03  eta: 0:05:49  time: 3.6800  data_time: 2.4292  memory: 5457  loss: 1.2258  loss_cls: 0.0000  loss_obj: 0.3071  loss_bbox: 0.9186
04/25 10:34:58 - mmengine - INFO - Exp name: yolov7_tiny_fast_1xb12-40e_cat_20230425_103413
04/25 10:34:58 - mmengine - INFO - Epoch(train)  [1][10/10]  lr: 3.0000e-03  eta: 0:04:12  time: 2.8025  data_time: 1.9631  memory: 5043  loss: 1.1485  loss_cls: 0.0000  loss_obj: 0.2723  loss_bbox: 0.8762
04/25 10:35:15 - mmengine - INFO - Epoch(train)  [2][ 5/10]  lr: 4.5536e-03  eta: 0:04:12  time: 2.9660  data_time: 2.3632  memory: 1175  loss: 1.1347  loss_cls: 0.0000  loss_obj: 0.2409  loss_bbox: 0.8938
04/25 10:35:21 - mmengine - INFO - Exp name: yolov7_tiny_fast_1xb12-40e_cat_20230425_103413
04/25 10:35:21 - mmengine - INFO - Epoch(train)  [2][10/10]  lr: 6.1799e-03  eta: 0:03:24  time: 2.5567  data_time: 2.0741  memory: 1175  loss: 1.0901  loss_cls: 0.0000  loss_obj: 0.2136  loss_bbox: 0.8765
04/25 10:35:40 - mmengine - INFO - Epoch(train)  [3][ 5/10]  lr: 7.2437e-03  eta: 0:03:27  time: 2.7721  data_time: 2.3503  memory: 1175  loss: 1.0772  loss_cls: 0.0000  loss_obj: 0.1920  loss_bbox: 0.8852
04/25 10:35:46 - mmengine - INFO - Exp name: yolov7_tiny_fast_1xb12-40e_cat_20230425_103413
04/25 10:35:46 - mmengine - INFO - Epoch(train)  [3][10/10]  lr: 8.7528e-03  eta: 0:02:57  time: 2.5409  data_time: 2.1685  memory: 1175  loss: 1.0861  loss_cls: 0.0000  loss_obj: 0.1721  loss_bbox: 0.9140
04/25 10:36:02 - mmengine - INFO - Epoch(train)  [4][ 5/10]  lr: 7.9595e-03  eta: 0:02:50  time: 2.6279  data_time: 2.2870  memory: 1175  loss: 1.0914  loss_cls: 0.0000  loss_obj: 0.1562  loss_bbox: 0.9352
04/25 10:36:08 - mmengine - INFO - Exp name: yolov7_tiny_fast_1xb12-40e_cat_20230425_103413
04/25 10:36:08 - mmengine - INFO - Epoch(train)  [4][10/10]  lr: 7.9595e-03  eta: 0:02:26  time: 2.4428  data_time: 2.1296  memory: 1175  loss: 1.0789  loss_cls: 0.0000  loss_obj: 0.1419  loss_bbox: 0.9371
04/25 10:36:22 - mmengine - INFO - Epoch(train)  [5][ 5/10]  lr: 7.9595e-03  eta: 0:02:16  time: 2.4822  data_time: 2.1863  memory: 1175  loss: 1.0818  loss_cls: 0.0000  loss_obj: 0.1325  loss_bbox: 0.9493
04/25 10:36:31 - mmengine - INFO - Exp name: yolov7_tiny_fast_1xb12-40e_cat_20230425_103413
04/25 10:36:31 - mmengine - INFO - Epoch(train)  [5][10/10]  lr: 7.9595e-03  eta: 0:02:00  time: 2.4158  data_time: 2.1357  memory: 1175  loss: 1.0982  loss_cls: 0.0000  loss_obj: 0.1243  loss_bbox: 0.9739
04/25 10:36:45 - mmengine - INFO - Epoch(train)  [6][ 5/10]  lr: 6.5796e-03  eta: 0:01:50  time: 2.3270  data_time: 2.1573  memory: 1175  loss: 1.0808  loss_cls: 0.0000  loss_obj: 0.0994  loss_bbox: 0.9813
04/25 10:36:53 - mmengine - INFO - Exp name: yolov7_tiny_fast_1xb12-40e_cat_20230425_103413
04/25 10:36:53 - mmengine - INFO - Epoch(train)  [6][10/10]  lr: 6.5796e-03  eta: 0:01:35  time: 2.2910  data_time: 2.1517  memory: 1175  loss: 1.0651  loss_cls: 0.0000  loss_obj: 0.0801  loss_bbox: 0.9849
04/25 10:37:11 - mmengine - INFO - Epoch(train)  [7][ 5/10]  lr: 5.0500e-03  eta: 0:01:26  time: 2.3269  data_time: 2.1856  memory: 1175  loss: 1.0597  loss_cls: 0.0000  loss_obj: 0.0671  loss_bbox: 0.9926
04/25 10:37:18 - mmengine - INFO - Exp name: yolov7_tiny_fast_1xb12-40e_cat_20230425_103413
04/25 10:37:18 - mmengine - INFO - Epoch(train)  [7][10/10]  lr: 5.0500e-03  eta: 0:01:11  time: 2.3315  data_time: 2.1903  memory: 1175  loss: 1.0696  loss_cls: 0.0000  loss_obj: 0.0601  loss_bbox: 1.0095
04/25 10:37:34 - mmengine - INFO - Epoch(train)  [8][ 5/10]  lr: 3.5204e-03  eta: 0:01:01  time: 2.2930  data_time: 2.1523  memory: 1175  loss: 1.0701  loss_cls: 0.0000  loss_obj: 0.0573  loss_bbox: 1.0127
04/25 10:37:42 - mmengine - INFO - Exp name: yolov7_tiny_fast_1xb12-40e_cat_20230425_103413
04/25 10:37:42 - mmengine - INFO - Epoch(train)  [8][10/10]  lr: 3.5204e-03  eta: 0:00:47  time: 2.3119  data_time: 2.1707  memory: 1175  loss: 1.0694  loss_cls: 0.0000  loss_obj: 0.0577  loss_bbox: 1.0117
04/25 10:37:57 - mmengine - INFO - Epoch(train)  [9][ 5/10]  lr: 2.1405e-03  eta: 0:00:36  time: 2.3029  data_time: 2.1610  memory: 1175  loss: 1.0699  loss_cls: 0.0000  loss_obj: 0.0604  loss_bbox: 1.0095
04/25 10:38:06 - mmengine - INFO - Exp name: yolov7_tiny_fast_1xb12-40e_cat_20230425_103413
04/25 10:38:06 - mmengine - INFO - Epoch(train)  [9][10/10]  lr: 2.1405e-03  eta: 0:00:23  time: 2.3628  data_time: 2.2196  memory: 1175  loss: 1.0727  loss_cls: 0.0000  loss_obj: 0.0652  loss_bbox: 1.0075
04/25 10:38:21 - mmengine - INFO - Epoch(train) [10][ 5/10]  lr: 1.0454e-03  eta: 0:00:12  time: 2.3832  data_time: 2.2410  memory: 1175  loss: 1.0446  loss_cls: 0.0000  loss_obj: 0.0677  loss_bbox: 0.9769
04/25 10:38:28 - mmengine - INFO - Exp name: yolov7_tiny_fast_1xb12-40e_cat_20230425_103413
04/25 10:38:28 - mmengine - INFO - Epoch(train) [10][10/10]  lr: 1.0454e-03  eta: 0:00:00  time: 2.3430  data_time: 2.2024  memory: 1175  loss: 1.0060  loss_cls: 0.0000  loss_obj: 0.0713  loss_bbox: 0.9348
04/25 10:38:28 - mmengine - INFO - Saving checkpoint at 10 epochs
04/25 10:38:34 - mmengine - INFO - Epoch(val) [10][ 5/28]    eta: 0:00:09  time: 0.4089  data_time: 0.1170  memory: 4434  
04/25 10:38:35 - mmengine - INFO - Epoch(val) [10][10/28]    eta: 0:00:05  time: 0.3060  data_time: 0.0846  memory: 4437  
04/25 10:38:36 - mmengine - INFO - Epoch(val) [10][15/28]    eta: 0:00:03  time: 0.2547  data_time: 0.0565  memory: 4434  
04/25 10:38:36 - mmengine - INFO - Epoch(val) [10][20/28]    eta: 0:00:01  time: 0.2121  data_time: 0.0603  memory: 202  
04/25 10:38:37 - mmengine - INFO - Epoch(val) [10][25/28]    eta: 0:00:00  time: 0.1865  data_time: 0.0623  memory: 202  
04/25 10:38:37 - mmengine - INFO - Evaluating bbox...
Loading and preparing results...
DONE (t=0.01s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=0.11s).
Accumulating evaluation results...
DONE (t=0.02s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.001
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.002
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.002
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.013
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.013
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.073
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.073
04/25 10:38:37 - mmengine - INFO - bbox_mAP_copypaste: 0.001 0.002 0.000 -1.000 -1.000 0.002
04/25 10:38:37 - mmengine - INFO - Epoch(val) [10][28/28]    coco/bbox_mAP: 0.0010  coco/bbox_mAP_50: 0.0020  coco/bbox_mAP_75: 0.0000  coco/bbox_mAP_s: -1.0000  coco/bbox_mAP_m: -1.0000  coco/bbox_mAP_l: 0.0020  data_time: 0.0622  time: 0.1743
04/25 10:38:41 - mmengine - INFO - The best checkpoint with 0.0010 coco/bbox_mAP at 10 epoch is saved to best_coco_bbox_mAP_epoch_10.pth.

**Comment by Qizong-Lu** [comment]
same problem i meet, what should i do?
