### ISSUE TITLE
【Question】invalid syntax & FileNotFoundError

### ISSUE THREAD

**Issue by Chenhanne** [open-mmlab/mmyolo#755]
I encounter this error when running my data set on a remote server using yolox. Howshould this be modified?
`Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/config/config.py", line 236, in _validate_py_syntax
    ast.parse(content)
  File "/root/miniconda3/lib/python3.8/ast.py", line 47, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 230
    'scale_factor'))
    ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 115, in <module>
    main()
  File "tools/train.py", line 59, in main
    cfg = Config.fromfile(args.config)
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/config/config.py", line 177, in fromfile
    cfg_dict, cfg_text, env_variables = Config._file2dict(
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/config/config.py", line 478, in _file2dict
    for base_cfg_path in Config._get_base_files(temp_config_file.name):
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/config/config.py", line 636, in _get_base_files
    Config._validate_py_syntax(filename)
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/config/config.py", line 238, in _validate_py_syntax
    raise SyntaxError('There are syntax errors in config '
SyntaxError: There are syntax errors in config file /tmp/tmpit__pswo/tmpr5grfp3o.py: invalid syntax (<unknown>, line 230)
Exception ignored in: <function _TemporaryFileCloser.__del__ at 0x7fb9d4bb45e0>
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/tempfile.py", line 440, in __del__
    self.close()
  File "/root/miniconda3/lib/python3.8/tempfile.py", line 436, in close
    unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpit__pswo/tmpr5grfp3o.py'
`

**Comment by RangeKing** [comment]
This is a basic question in python. Please check your config file referring to https://realpython.com/invalid-syntax-python/.

**Comment by Chenhanne** [comment]
Thank you so much!
