### ISSUE TITLE
About the conversion of New config

### ISSUE THREAD

**Issue by JimmyMa99** [open-mmlab/mmyolo#824]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmyolo/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmyolo.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmyolo).

### 🐞 Describe the bug

[](https://aicarrier.feishu.cn/docx/PkICdaJbpoOVjLxMFi2cYqPjnOc)
我根据以上链接进行配置，将 `yolov5_s_v61_syncbn_8xb16_300e_coco.py` 和 `yolov5_s_p6_v62_syncbn_fast_8xb16_300e_coco.py` 进行转换，应该是哪里没有处理好，使用检查脚本的时候报以下错误
'''
  File "/home/mzm/miniconda3/envs/mmyolo/lib/python3.8/site-packages/mmengine/config/config.py", line 54, in __getattr__
    raise AttributeError(f"'{self.__class__.__name__}' object has no "
AttributeError: 'ConfigDict' object has no attribute 'backend_args'
Exception ignored in: <function _TemporaryFileCloser.__del__ at 0x7f575c1ea040>
Traceback (most recent call last):
  File "/home/mzm/miniconda3/envs/mmyolo/lib/python3.8/tempfile.py", line 440, in __del__
    self.close()
  File "/home/mzm/miniconda3/envs/mmyolo/lib/python3.8/tempfile.py", line 436, in close
    unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpm3ae0u06/tmpckz9v6td.py'
Exception ignored in: <function _TemporaryFileCloser.__del__ at 0x7f575c1ea040>
Traceback (most recent call last):
  File "/home/mzm/miniconda3/envs/mmyolo/lib/python3.8/tempfile.py", line 440, in __del__
    self.close()
  File "/home/mzm/miniconda3/envs/mmyolo/lib/python3.8/tempfile.py", line 436, in close
    unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpk23lew_s/tmpn8yojazq.py'
Exception ignored in: <function _TemporaryFileCloser.__del__ at 0x7f575c1ea040>
Traceback (most recent call last):
  File "/home/mzm/miniconda3/envs/mmyolo/lib/python3.8/tempfile.py", line 440, in __del__
    self.close()
  File "/home/mzm/miniconda3/envs/mmyolo/lib/python3.8/tempfile.py", line 436, in close
    unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpzx0me_lr/tmp5j3y57vu.py'
'''
这是转换后的结果
[config.zip](https://github.com/open-mmlab/mmyolo/files/11958264/config.zip)

### Environment

具体的环境是按照文档配置的一模一样

**Comment by FunnyWii** [comment]
在画特征图的时候也报错AttributeError: 'ConfigDict' object has no attribute 'backend_args' 请问你是咋解决的
