### ISSUE TITLE
train.py: error: unrecognized arguments: --local-rank=1

### ISSUE THREAD

**Issue by ATang0729** [open-mmlab/mmyolo#839]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmyolo/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmyolo.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmyolo).

### 🐞 Describe the bug

When I trained yolov7 on my customized dataset based on `yolov7_l_syncbn_fast_8x16b-300e_coco.py` and using the command `bash tools/dist_train.sh $CONFIG $GPUS`, I encountered the following error:
```
usage: train.py [-h] [--work-dir WORK_DIR] [--amp] [--resume [RESUME]]
                [--cfg-options CFG_OPTIONS [CFG_OPTIONS ...]]
                [--launcher {none,pytorch,slurm,mpi}]
                [--local_rank LOCAL_RANK]
                config
train.py: error: unrecognized arguments: --local-rank=0
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 2) local_rank: 0 (pid: 118494) of binary: /HOME/scz0p8p/.conda/envs/openmmlab/bin/python
Traceback (most recent call last):
  File "/HOME/scz0p8p/.conda/envs/openmmlab/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/HOME/scz0p8p/.conda/envs/openmmlab/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/HOME/scz0p8p/.conda/envs/openmmlab/lib/python3.8/site-packages/torch/distributed/launch.py", line 196, in <module>
    main()
  File "/HOME/scz0p8p/.conda/envs/openmmlab/lib/python3.8/site-packages/torch/distributed/launch.py", line 192, in main
    launch(args)
  File "/HOME/scz0p8p/.conda/envs/openmmlab/lib/python3.8/site-packages/torch/distributed/launch.py", line 177, in launch
    run(args)
  File "/HOME/scz0p8p/.conda/envs/openmmlab/lib/python3.8/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/HOME/scz0p8p/.conda/envs/openmmlab/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/HOME/scz0p8p/.conda/envs/openmmlab/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
```

### Environment

sys.platform: linux
Python: 3.8.17 (default, Jul  5 2023, 21:04:15) [GCC 11.2.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0: NVIDIA GeForce RTX 3090
CUDA_HOME: /data/apps/cuda/11.7
NVCC: Cuda compilation tools, release 11.7, V11.7.64
GCC: gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
PyTorch: 2.0.1+cu117
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2023.1-Product Build 20230303 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.7.3 (Git Hash 6dbeffbae1f23cbbeae17adb7b5b13f1f37c080e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.7
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.5
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.0.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.15.2
OpenCV: 4.8.0
MMEngine: 0.8.2
MMCV: 2.0.1
MMDetection: 3.0.0
MMYOLO: 0.5.0+

### Additional information

# References
> 1. [解决报错:train.py: error: unrecognized arguments: --local-rank=1 ERROR:torch.distributed.elastic.multipr](http://t.csdn.cn/LjJyW)
> 2. #796 

# My Guess
In my humble opinion, it is due to the "wrong" set of the input paramter `--local_rank` in `tools/train.py`. 

# My Solutions 
## 1. Simply change `--local_rank` to `--local-rank`
According to No.1 reference, in torch V2.0+, it has been changed to `--local-rank` in `launch.py`. So I modified the source code of `tools/train.py` and the orinal error disappeared, but a new one rose (I don't know whether the new one has to do with I have done):
```
Traceback (most recent call last):
  File "tools/train.py", line 115, in <module>
    main()
  File "tools/train.py", line 111, in main
    runner.train()
  File "/HOME/scz0p8p/.conda/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1735, in train
    model = self.train_loop.run()  # type: ignore
  File "/HOME/scz0p8p/.conda/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/loops.py", line 96, in run
    self.run_epoch()
  File "/HOME/scz0p8p/.conda/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/loops.py", line 111, in run_epoch
    for idx, data_batch in enumerate(self.dataloader):
  File "/HOME/scz0p8p/.conda/envs/openmmlab/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 436, in __iter__
    self._iterator = self._get_iterator()
  File "/HOME/scz0p8p/.conda/envs/openmmlab/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 388, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/HOME/scz0p8p/.conda/envs/openmmlab/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1061, in __init__
    pin_memory_thread.start()
  File "/HOME/scz0p8p/.conda/envs/openmmlab/lib/python3.8/threading.py", line 852, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 94004 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 94005 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 94006 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 94007 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 94008 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 94010 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 94011 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 5 (pid: 94009) of binary: /HOME/scz0p8p/.conda/envs/openmmlab/bin/python
Traceback (most recent call last):
  File "/HOME/scz0p8p/.conda/envs/openmmlab/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/HOME/scz0p8p/.conda/envs/openmmlab/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/HOME/scz0p8p/.conda/envs/openmmlab/lib/python3.8/site-packages/torch/distributed/launch.py", line 196, in <module>
    main()
  File "/HOME/scz0p8p/.conda/envs/openmmlab/lib/python3.8/site-packages/torch/distributed/launch.py", line 192, in main
    launch(args)
  File "/HOME/scz0p8p/.conda/envs/openmmlab/lib/python3.8/site-packages/torch/distributed/launch.py", line 177, in launch
    run(args)
  File "/HOME/scz0p8p/.conda/envs/openmmlab/lib/python3.8/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/HOME/scz0p8p/.conda/envs/openmmlab/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/HOME/scz0p8p/.conda/envs/openmmlab/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
```

## 2. Use torch V1.10
Successed. And if in this way, maybe the [doc](https://mmyolo.readthedocs.io/en/latest/get_started/dependencies.html) should warn users not to install torch>=2.0.0

**Comment by hhaAndroid** [comment]
@ATang0729 Fixed

**Comment by Evolive2** [comment]
For this issue, I have an alternative solution that doesn't require reverting to PyTorch 1.x.
Firstly, this problem arises because in PyTorch 2.0, the torch.distributed.launch will pass the --local-rank parameter to tools/train.py instead of --local_rank. So, we should modify the parser.add_argument('--local_rank', type=int, default=0) in train.py to parser.add_argument('--local_rank', '--local-rank', type=int, default=0). If after making this change, you encounter a new error related to TypeError: FormatCode() got an unexpected keyword argument 'verify', you can resolve it by using pip install yapf==0.40.1

**Comment by Evolive2** [comment]
For this issue, I have an alternative solution that doesn't require reverting to PyTorch 1.x. 
Firstly, this problem arises because in PyTorch 2.0, the torch.distributed.launch will pass the --local-rank parameter to tools/train.py instead of --local_rank. So, we should modify "parser.add_argument('--local_rank', type=int, default=0)" in train.py to "parser.add_argument('--local_rank', '--local-rank', type=int, default=0)". 
If after making this change, you encounter a new error related to "TypeError: FormatCode() got an unexpected keyword argument 'verify'", you can resolve it by using 'pip install yapf==0.40.1'
