### ISSUE TITLE
YOLOV8 Evaluating got errors

### ISSUE THREAD

**Issue by o0GoldLike0o** [open-mmlab/mmyolo#843]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmyolo/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmyolo.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmyolo).

### 🐞 Describe the bug

1、loss start with zero
2、Evaluating got errors

### Environment

sys.platform: linux
Python: 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0: Tesla T4
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.8, V11.8.89
GCC: x86_64-linux-gnu-gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PyTorch: 1.13.0a0+936e930
PyTorch compiling details: PyTorch built with:
  - GCC 9.4
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.1-Product Build 20201104 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash N/A)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.8
  - NVCC architecture flags: -gencode;arch=compute_52,code=sm_52;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90;-gencode;arch=compute_90,code=compute_90
  - CuDNN 8.7
  - Magma 2.6.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.8, CUDNN_VERSION=8.7.0, CXX_COMPILER=/usr/bin/c++, CXX_FLAGS=-fno-gnu-unique -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=ON, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.15.0a0
OpenCV: 4.6.0
MMEngine: 0.8.3
MMCV: 2.0.1
MMDetection: 3.0.0
MMYOLO: 0.5.0+

### Additional information

I got 2 problems:
### when I have background images which means there is no label files, the loss start with 0.000
08/04 03:09:51 - mmengine - INFO - Load checkpoint from https://download.openmmlab.com/mmyolo/v0/yolov5/yolov5_s-v61_syncbn_fast_8xb16-300e_coco/yolov5_s-v61_syncbn_fast_8xb16-300e_coco_20220918_084700-86e02187.pth
08/04 03:09:51 - mmengine - WARNING - "FileClient" will be deprecated in future. Please use io functions in https://mmengine.readthedocs.io/en/latest/api/fileio.html#file-io
08/04 03:09:51 - mmengine - WARNING - "HardDiskBackend" is the alias of "LocalBackend" and the former will be deprecated in future.
08/04 03:09:51 - mmengine - INFO - Checkpoints will be saved to /tmp/detect/detect-train/work_dirs/yolov5_s_puman.
08/04 03:10:00 - mmengine - INFO - Epoch(train)  [1][   5/7586]  base_lr: 1.0000e-02 lr: 1.7576e-06  eta: 6 days, 10:42:14  time: 1.8354  data_time: 0.8389  memory: 3782  loss: 0.4921  loss_cls: 0.0000  loss_obj: 0.4921  loss_bbox: 0.0000
08/04 03:10:01 - mmengine - INFO - Epoch(train)  [1][  10/7586]  base_lr: 1.0000e-02 lr: 3.9547e-06  eta: 3 days, 12:08:49  time: 0.9984  data_time: 0.4202  memory: 1689  loss: 0.4656  loss_cls: 0.0000  loss_obj: 0.4656  loss_bbox: 0.0000
08/04 03:10:01 - mmengine - INFO - Epoch(train)  [1][  15/7586]  base_lr: 1.0000e-02 lr: 6.1517e-06  eta: 2 days, 12:38:38  time: 0.7195  data_time: 0.2806  memory: 1689  loss: 0.4390  loss_cls: 0.0000  loss_obj: 0.4390  loss_bbox: 0.0000
08/04 03:10:04 - mmengine - INFO - Epoch(train)  [1][  20/7586]  base_lr: 1.0000e-02 lr: 8.3487e-06  eta: 2 days, 8:55:19  time: 0.6754  data_time: 0.3061  memory: 1689  loss: 0.4143  loss_cls: 0.0000  loss_obj: 0.4143  loss_bbox: 0.0000
08/04 03:10:06 - mmengine - INFO - Epoch(train)  [1][  25/7586]  base_lr: 1.0000e-02 lr: 1.0546e-05  eta: 2 days, 3:10:00  time: 0.6071  data_time: 0.2784  memory: 1689  loss: 0.3922  loss_cls: 0.0000  loss_obj: 0.3922  loss_bbox: 0.0000
08/04 03:10:08 - mmengine - INFO - Epoch(train)  [1][  30/7586]  base_lr: 1.0000e-02 lr: 1.2743e-05  eta: 2 days, 1:39:12  time: 0.5891  data_time: 0.2885  memory: 1689  loss: 0.3726  loss_cls: 0.0000  loss_obj: 0.3726  loss_bbox: 0.0000
08/04 03:10:11 - mmengine - INFO - Epoch(train)  [1][  35/7586]  base_lr: 1.0000e-02 lr: 1.4940e-05  eta: 2 days, 1:00:54  time: 0.5816  data_time: 0.3012  memory: 1689  loss: 0.3552  loss_cls: 0.0000  loss_obj: 0.3552  loss_bbox: 0.0000
08/04 03:10:12 - mmengine - INFO - Epoch(train)  [1][  40/7586]  base_lr: 1.0000e-02 lr: 1.7137e-05  eta: 1 day, 21:25:40  time: 0.5390  data_time: 0.2739  memory: 1689  loss: 0.3397  loss_cls: 0.0000  loss_obj: 0.3397  loss_bbox: 0.0000
08/04 03:10:15 - mmengine - INFO - Epoch(train)  [1][  45/7586]  base_lr: 1.0000e-02 lr: 1.9334e-05  eta: 1 day, 21:48:52  time: 0.5436  data_time: 0.2903  memory: 1689  loss: 0.3257  loss_cls: 0.0000  loss_obj: 0.3257  loss_bbox: 0.0000
08/04 03:10:19 - mmengine - INFO - Epoch(train)  [1][  50/7586]  base_lr: 1.0000e-02 lr: 2.1531e-05  eta: 1 day, 23:06:37  time: 0.5590  data_time: 0.3141  memory: 1689  loss: 0.3131  loss_cls: 0.0000  loss_obj: 0.3131  loss_bbox: 0.0000
08/04 03:10:20 - mmengine - INFO - Epoch(train)  [1][  55/7586]  base_lr: 1.0000e-02 lr: 2.3728e-05  eta: 1 day, 20:32:24  time: 0.3978  data_time: 0.2364  memory: 1689  loss: 0.2826  loss_cls: 0.0000  loss_obj: 0.2826  loss_bbox: 0.0000
08/04 03:10:22 - mmengine - INFO - Epoch(train)  [1][  60/7586]  base_lr: 1.0000e-02 lr: 2.5925e-05  eta: 1 day, 20:27:27  time: 0.4334  data_time: 0.2719  memory: 1689  loss: 0.2563  loss_cls: 0.0000  loss_obj: 0.2563  loss_bbox: 0.0000
08/04 03:10:24 - mmengine - INFO - Epoch(train)  [1][  65/7586]  base_lr: 1.0000e-02 lr: 2.8122e-05  eta: 1 day, 19:21:51  time: 0.4531  data_time: 0.2916  memory: 1689  loss: 0.2343  loss_cls: 0.0000  loss_obj: 0.2343  loss_bbox: 0.0000
08/04 03:10:27 - mmengine - INFO - Epoch(train)  [1][  70/7586]  base_lr: 1.0000e-02 lr: 3.0319e-05  eta: 1 day, 19:06:04  time: 0.4459  data_time: 0.2844  memory: 1689  loss: 0.2160  loss_cls: 0.0000  loss_obj: 0.2160  loss_bbox: 0.0000
### when I change the other datasets, I got another problem
08/04 12:00:42 - mmengine - INFO - Exp name: yolov8_s_syncbn_fast_8xb16-500e_coco_20230804_115200
08/04 12:00:42 - mmengine - INFO - Saving checkpoint at 5 epochs
08/04 12:00:44 - mmengine - WARNING - `save_param_scheduler` is True but `self.param_schedulers` is None, so skip saving parameter schedulers
08/04 12:00:57 - mmengine - INFO - Epoch(val)   [5][ 50/110]    eta: 0:00:14  time: 0.2459  data_time: 0.0159  memory: 7682  
08/04 12:01:05 - mmengine - INFO - Epoch(val)   [5][100/110]    eta: 0:00:02  time: 0.1582  data_time: 0.0013  memory: 1049  
08/04 12:01:09 - mmengine - INFO - Evaluating bbox...
Loading and preparing results...
DONE (t=0.04s)
Creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=3.00s).
Accumulating evaluation results...
DONE (t=0.52s).
Traceback (most recent call last):
  File "train.py", line 115, in <module>
    main()
  File "train.py", line 111, in main
    runner.train()
  File "/usr/local/lib/python3.8/dist-packages/mmengine/runner/runner.py", line 1745, in train
    model = self.train_loop.run()  # type: ignore
  File "/usr/local/lib/python3.8/dist-packages/mmengine/runner/loops.py", line 102, in run
    self.runner.val_loop.run()
  File "/usr/local/lib/python3.8/dist-packages/mmengine/runner/loops.py", line 366, in run
    metrics = self.evaluator.evaluate(len(self.dataloader.dataset))
  File "/usr/local/lib/python3.8/dist-packages/mmengine/evaluator/evaluator.py", line 79, in evaluate
    _results = metric.evaluate(size)
  File "/usr/local/lib/python3.8/dist-packages/mmengine/evaluator/metric.py", line 133, in evaluate
    _metrics = self.compute_metrics(results)  # type: ignore
  File "/usr/local/lib/python3.8/dist-packages/mmdet/evaluation/metrics/coco_metric.py", line 512, in compute_metrics
    coco_eval.summarize()
  File "/usr/local/lib/python3.8/dist-packages/pycocotools/cocoeval.py", line 518, in summarize
    self.stats = summarize()
  File "/usr/local/lib/python3.8/dist-packages/pycocotools/cocoeval.py", line 485, in _summarizeDets
    stats[0] = _summarize(1)
  File "/usr/local/lib/python3.8/dist-packages/pycocotools/cocoeval.py", line 469, in _summarize
    s = s[:,aind,mind,:,:]
IndexError: index 2 is out of bounds for axis 2 with size 1

**Comment by todesti2** [comment]
Hi, have you solved this problem, I'm also experiencing this error
