### ISSUE TITLE
python tools/analysis_tools/optimize_anchors.py报错！！！

### ISSUE THREAD

**Issue by LYKlyk** [open-mmlab/mmyolo#847]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmyolo/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmyolo.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmyolo).

### 🐞 Describe the bug

当采用COCO格式进行注释，并且数据集中所有图片的大小为1280*720时，运行以下命令：python tools/analysis_tools/optimize_anchors.py ./configs/ipstrash/yolov5_n.py --algorithm v5-k-means就会报错：

(mmyolo) xjtuuser@ubuntu:~/mmyolo$ python tools/analysis_tools/optimize_anchors.py ./configs/ipstrash/yolov5_n.py --algorithm v5-k-means --input-shape 1280 720 --prior-match-thr 4.0 --out-dir work_dirs/dataset_analysis_ipstrash
loading annotations into memory...
Done (t=0.09s)
creating index...
index created!
08/09 14:51:48 - mmengine - INFO - Collecting bboxes from annotation...
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 3200/3200, 8147.1 task/s, elapsed: 0s, ETA:     0ss

08/09 14:51:48 - mmengine - INFO - Collected 0 bboxes.
Traceback (most recent call last):
  File "tools/analysis_tools/optimize_anchors.py", line 648, in <module>
    main()
  File "tools/analysis_tools/optimize_anchors.py", line 628, in main
    optimizer = YOLOV5KMeansAnchorOptimizer(
  File "tools/analysis_tools/optimize_anchors.py", line 295, in __init__
    super().__init__(**kwargs)
  File "tools/analysis_tools/optimize_anchors.py", line 140, in __init__
    ratios = img_shapes.max(1, keepdims=True) / np.array([input_shape])
  File "/raid/xjtuuser/anaconda3/envs/mmyolo/lib/python3.8/site-packages/numpy/core/_methods.py", line 41, in _amax
    return umr_maximum(a, axis, None, out, keepdims, initial, where)
numpy.AxisError: axis 1 is out of bounds for array of dimension 1

我们发现排除后发现就是图片尺寸大小问题，如果图片的尺寸大小为1280*1000，就不会出错。但是，为什么会造成这种原因？如何解决这种原因？

### Environment

(mmyolo) xjtuuser@ubuntu:~/mmyolo$ python mmyolo/utils/collect_env.py
sys.platform: linux
Python: 3.8.17 (default, Jul  5 2023, 21:04:15) [GCC 11.2.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0,1,2,3,4,5,6,7: Tesla V100-SXM2-16GB
CUDA_HOME: None
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PyTorch: 1.13.1+cu117
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2023.1-Product Build 20230303 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.7
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.5
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.14.1+cu117
OpenCV: 4.8.0
MMEngine: 0.8.4
MMCV: 2.0.1
MMDetection: 3.0.0
MMYOLO: 0.6.0+

**Comment by yexiao11** [comment]
请问解决了吗
