### ISSUE TITLE
执行mim install -r requirements/mminstall.txt 但下载的是mmdet=2.17.0 (Ran 'mim install -r requirements/mminstall.txt' but downloaded 'mmdet=2.17.0'.)

### ISSUE THREAD

**Issue by little-spoon** [open-mmlab/mmyolo#869]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmyolo/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmyolo.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmyolo).

### 🐞 Describe the bug

在安装mmyolo的时候，执行
`mim install -r requirements/mminstall.txt`
但是从输出内容里面看是这样的：
```
Collecting mmdet==2.17.0
  Using cached mmdet-2.17.0.tar.gz (652 kB)
  Preparing metadata (setup.py) ... done
Saved /tmp/tmpuo186zhk/mmdet-2.17.0.tar.gz
Collecting mmdet==2.17.0
  Using cached mmdet-2.17.0.tar.gz (652 kB)
  Preparing metadata (setup.py) ... done
Saved /tmp/tmpyhrd2lfi/mmdet-2.17.0.tar.gz
Collecting mmdet==2.17.0
  Using cached mmdet-2.17.0.tar.gz (652 kB)
  Preparing metadata (setup.py) ... done
Saved /tmp/tmpugvb_ymc/mmdet-2.17.0.tar.gz
Collecting mmdet==2.17.0
  Using cached mmdet-2.17.0.tar.gz (652 kB)
  Preparing metadata (setup.py) ... done
Saved /tmp/tmppl53kf3q/mmdet-2.17.0.tar.gz
Collecting mmdet==2.17.0
  Using cached mmdet-2.17.0.tar.gz (652 kB)
  Preparing metadata (setup.py) ... done
Saved /tmp/tmpy3pqbal5/mmdet-2.17.0.tar.gz
Collecting mmdet==2.17.0
  Using cached mmdet-2.17.0.tar.gz (652 kB)
  Preparing metadata (setup.py) ... done
Saved /tmp/tmpyg5lwrt5/mmdet-2.17.0.tar.gz

```
并且最后会报错：
```
pip download failed with args: ['mmdet==2.17.0', '-d', '/tmp/tmpxf4wdyli', '--no-deps', '--no-binary', ':all:']
ERROR: Exception:
Traceback (most recent call last):
  File "/home/host/mounted2/anaconda3/envs/mmyolo/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
  File "/home/host/mounted2/anaconda3/envs/mmyolo/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 248, in wrapper
    return func(self, options, args)
  File "/home/host/mounted2/anaconda3/envs/mmyolo/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 444, in run
    conflicts = self._determine_conflicts(to_install)
  File "/home/host/mounted2/anaconda3/envs/mmyolo/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 575, in _determine_conflicts
    return check_install_conflicts(to_install)
  File "/home/host/mounted2/anaconda3/envs/mmyolo/lib/python3.8/site-packages/pip/_internal/operations/check.py", line 106, in check_install_conflicts
    package_set, _ = create_package_set_from_installed()
  File "/home/host/mounted2/anaconda3/envs/mmyolo/lib/python3.8/site-packages/pip/_internal/operations/check.py", line 45, in create_package_set_from_installed
    dependencies = list(dist.iter_dependencies())
  File "/home/host/mounted2/anaconda3/envs/mmyolo/lib/python3.8/site-packages/pip/_internal/metadata/pkg_resources.py", line 216, in iter_dependencies
    return self._dist.requires(extras)
  File "/home/host/mounted2/anaconda3/envs/mmyolo/lib/python3.8/site-packages/mim/commands/install.py", line 207, in patched_requires
    mmdeps_text = get_mmdeps_from_mmpkg(self.project_name,
  File "/home/host/mounted2/anaconda3/envs/mmyolo/lib/python3.8/site-packages/mim/commands/install.py", line 321, in get_mmdeps_from_mmpkg
    mminstall_content = get_mminstall_from_pypi(mmpkg, index_url=index_url)
  File "/home/host/mounted2/anaconda3/envs/mmyolo/lib/python3.8/site-packages/mim/commands/install.py", line 351, in get_mminstall_from_pypi
    exit(status_code)
  File "/home/host/mounted2/anaconda3/envs/mmyolo/lib/python3.8/_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: 2
```

### Environment

在此之前，我执行了以下命令：
```
conda create -n mmyolo python=3.8 -y
conda activate mmyolo
conda install pytorch==1.8.0 torchvision==0.9.0 torchaudio==0.8.0 cudatoolkit=11.1 -c pytorch -c conda-forge -y
git clone https://github.com/open-mmlab/mmyolo.git
cd mmyolo
pip install -U openmim
mim install -r requirements/mminstall.txt
```
在我的环境中执行`nvcc -V`，显示：
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Oct_12_20:09:46_PDT_2020
Cuda compilation tools, release 11.1, V11.1.105
Build cuda_11.1.TC455_06.29190527_0
```
执行`nvidia-smi`显示的第一行：
` NVIDIA-SMI 470.86       Driver Version: 470.86       CUDA Version: 11.4   `

### Additional information

请各位帮我看看是哪里出了问题，感谢感谢！

**Comment by little-spoon** [comment]
我又新建了一个环境，执行的下面这个语句安装pytorch`conda install pytorch torchvision -c pytorch`，结果还是一样的，还是会报错并且还是显示装的是mmdet=2.17.0
