### ISSUE TITLE
yolov7_to_mmyolo.py error

### ISSUE THREAD

**Issue by chuong98** [open-mmlab/mmyolo#875]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmyolo/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmyolo.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmyolo).

### 🐞 Describe the bug

I tested the command:
`tools/model_converters/yolov7_to_mmyolo.py` on Yolov7-w6. 
It ran successfully up to layer 117, then throw the following error:
```bash
Convert model.117.conv.weight to bbox_head.head_module.main_convs_pred.3.0.conv.weight
Convert model.117.bn.weight to bbox_head.head_module.main_convs_pred.3.0.bn.weight
Convert model.117.bn.bias to bbox_head.head_module.main_convs_pred.3.0.bn.bias
Convert model.117.bn.running_mean to bbox_head.head_module.main_convs_pred.3.0.bn.running_mean
Convert model.117.bn.running_var to bbox_head.head_module.main_convs_pred.3.0.bn.running_var
Convert model.117.bn.num_batches_tracked to bbox_head.head_module.main_convs_pred.3.0.bn.num_batches_tracked
Traceback (most recent call last):
  File "/root/workspace/yolov7/yolov7_to_mmyolo.py", line 1093, in <module>
    main()
  File "/root/workspace/yolov7/yolov7_to_mmyolo.py", line 1085, in main
    convert(args.src, args.dst)
  File "/root/workspace/yolov7/yolov7_to_mmyolo.py", line 1051, in convert
    convert_dict['.'.join(strs_key)])
KeyError: 'model.118.conv.weight'
```

### Environment

sys.platform: linux
Python: 3.10.12 (main, Jul  5 2023, 18:54:27) [GCC 11.2.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0,1,2,3: Quadro RTX 8000
CUDA_HOME: /usr/local/cuda-11.8/
GCC: gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
PyTorch: 2.0.1+cu117
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.7.3 (Git Hash 6dbeffbae1f23cbbeae17adb7b5b13f1f37c080e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.7
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.5
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.0.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.15.1a0+60a3e72
OpenCV: 4.6.0
MMEngine: 0.8.4
MMCV: 2.0.0
MMDetection: 3.1.0
MMYOLO: 0.6.0+84932d7

### Additional information

I printed the state dict keys from the official Yolov7, and found there are layers from 118-->122 that are not included in the mmyolo converter code.
In addition, layer 122 is the box_head instead of layer 118. 
I think the `convert_dict_w ` is not correct for yolov7-w6.

**Comment by SikaAntler** [comment]
Have you solve this problem? I have encountered similar error when converted yolov5l.pt to mmyolo format. The error is: KeyError: 'model.9.cv3'. I checked the key 'model.9.cv3' was not in the convert_dict.

**Comment by chuong98** [comment]
I don't remember exactly, but here are the step that I would do:
- Modify the scrip 'yolov7_to_mmyolo.py' to create a Mapping Dict: map_dict={Yolov7_key:mmyolo_key}.
- Loop over the key of `yolov7` statedict to find unmatched keys: 
```python
umatch_yolov7=[k for k in yolov7.state_dict().keys() if k not in list(map_dict.keys())]
```
- Loop over the key of `mmyolo` statedict to find unmatched keys: 
```python
umatch_mmyolov=[k for k in mmyolo.state_dict().keys() if k not in list(map_dict.values())]
```
- Manually match the `umatch_yolov7` with `umatch_mmyolov`, then append the result to `map_dict`

**Comment by SikaAntler** [comment]
> I don't remember exactly, but here are the step that I would do:
> 
> * Modify the scrip 'yolov7_to_mmyolo.py' to create a Mapping Dict: map_dict={Yolov7_key:mmyolo_key}.
> * Loop over the key of `yolov7` statedict to find unmatched keys:
> 
> ```python
> umatch_yolov7=[k for k in yolov7.state_dict().keys() if k not in list(map_dict.keys())]
> ```
> 
> * Loop over the key of `mmyolo` statedict to find unmatched keys:
> 
> ```python
> umatch_mmyolov=[k for k in mmyolo.state_dict().keys() if k not in list(map_dict.values())]
> ```
> 
> * Manually match the `umatch_yolov7` with `umatch_mmyolov`, then append the result to `map_dict`

Thank you for your reply. I have found the problem was that the given weights was trained by the early version of yolov5 released, which contained module like 'Focus'. I succesfully converted the weights download from official repository.
