### ISSUE TITLE
15_minutes_object_detection tutorial error in docker

### ISSUE THREAD

**Issue by keeper-jie** [open-mmlab/mmyolo#893]
### 📚 The doc issue

When I use command as https://mmyolo.readthedocs.io/zh_CN/latest/get_started/15_minutes_object_detection.html#easydeploy
```
python projects/easydeploy/tools/export.py \
    configs/yolov5/yolov5_s-v61_fast_1xb12-40e_cat.py \
    work_dirs/yolov5_s-v61_fast_1xb12-40e_cat/epoch_40.pth \
    --work-dir work_dirs/yolov5_s-v61_fast_1xb12-40e_cat \
    --img-size 640 640 \
    --batch 1 \
    --device cuda:0 \
    --simplify \
    --opset 11 \
    --backend 2 \
    --pre-topk 1000 \
    --keep-topk 100 \
    --iou-threshold 0.65 \
    --score-threshold 0.25
```
first problem is `python: can't open file '../projects/easydeploy/tools/export.py': [Errno 2] No such file or directory`  
I changed it as `projects/easydeploy/tools/export_onnx.py` but error occur again  `ValueError: '2' is not a valid MMYOLOBackend`  
So I have viewed the code of `projects/easydeploy/tools/export_onnx.py`, change command to 
```
python ../projects/easydeploy/tools/export_onnx.py \
	    ../configs/yolov5/yolov5_s-v61_fast_1xb12-40e_cat.py \
	    ../work_dirs/yolov5_s-v61_fast_1xb12-40e_cat/epoch_40.pth \
	    --work-dir ../work_dirs/yolov5_s-v61_fast_1xb12-40e_cat \
        --img-size 640 640 \
        --batch 1 \
        --device cuda:0 \
        --simplify \
        --opset 11 \
        --backend tensorrt8 \
        --pre-topk 1000 \
        --keep-topk 100 \
        --iou-threshold 0.65 \
        --score-threshold 0.25
```
onnx output suc
but  ERROR occur when I run 
```
python ../projects/easydeploy/tools/build_engine.py \
        ../work_dirs/yolov5_s-v61_fast_1xb12-40e_cat/epoch_40.onnx \
        --img-size 640 640 \
        --device cuda:0
```
ERROR: 
```
[09/26/2023-08:29:22] [TRT] [W] Unable to determine GPU memory usage
[09/26/2023-08:29:22] [TRT] [W] CUDA initialization failure with error: 35. Please check your CUDA installation:  http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html
Traceback (most recent call last):
  File "../projects/easydeploy/tools/build_engine.py", line 136, in <module>
    main(args)
  File "../projects/easydeploy/tools/build_engine.py", line 131, in main
    builder.build(scales, fp16=args.fp16)
  File "../projects/easydeploy/tools/build_engine.py", line 96, in build
    self.__build_engine(scale, fp16, with_profiling)
  File "../projects/easydeploy/tools/build_engine.py", line 42, in __build_engine
    builder = trt.Builder(logger)
TypeError: pybind11::init(): factory function returned nullptr
```
I have used `import tensorrt;print(tensorrt.__version__)` to output tensorRT version which output `8.6.1`, I do not know how to solve this problem.

### Suggest a potential alternative/fix

After update source code, the most important thing is that test tutorial ipynb working or not. Because everyone will use this tutorial to test mmyolo, a lot of beginner will give up if the experience is bad.

**Comment by keeper-jie** [comment]
When I retry run yolo docker, it suc, step as followed:
# build docker container
1. download code zip from https://github.com/open-mmlab/mmyolo/tree/main
2. （Optinal for china user）uncomment `/mmyolo/docker/Dockerfile` 
```
RUN sed -i 's/http:\/\/archive.ubuntu.com\/ubuntu\//http:\/\/mirrors.aliyun.com\/ubuntu\//g' /etc/apt/sources.list && \
   pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
```
3. pull docker image(where 6006 is tensorBoard default port)
```
export DATA_DIR=/path/to/your/dataset
docker run --gpus all run -p 6006:6006 --shm-size=8g -it -v ${DATA_DIR}:/mmyolo/data mmyolo
```
# develop mmyolo by vscode
4.install vscode ssh, docker plugin and enter docker mmyolo container
5.open `/mmyolo/demo/15_minutes_object_detection.ipynb` in vscode
6.run cell and install `jupyter+python` plugin suggested
7.open vscode terminal and run `pip install ipykernel`
# quick-start by trian test deploy
8. download data by
```
!python ../tools/misc/download_dataset.py --dataset-name cat --save-dir ../data/cat --unzip --delete
```
## train
9.min install albumentations by `!mim install -r ../requirements/albu.txt`
10.train by `!cd .. && python ./tools/train.py ./configs/yolov5/yolov5_s-v61_fast_1xb12-40e_cat.py`
## test
11.test by 
```
!cd ..&& python tools/test.py configs/yolov5/yolov5_s-v61_fast_1xb12-40e_cat.py \
                      work_dirs/yolov5_s-v61_fast_1xb12-40e_cat/epoch_40.pth \
                      --show-dir show_results
```
## deploy
12.install deploy env
```
%pip install onnx
%pip install onnx-simplifier # Install if you want to use simplify
%pip install tensorrt        # If you have GPU environment and need to output TensorRT model you need to continue execution
!pip install onnxruntime
```
13.export cpu onnx
```
!cd .. && python projects/easydeploy/tools/export_onnx.py \
    configs/yolov5/yolov5_s-v61_fast_1xb12-40e_cat.py \
    work_dirs/yolov5_s-v61_fast_1xb12-40e_cat/epoch_40.pth \
    --work-dir work_dirs/yolov5_s-v61_fast_1xb12-40e_cat \
    --img-size 640 640 \
    --batch 1 \
    --device cpu \
    --simplify \
    --opset 11 \
    --backend ONNXRUNTIME \
    --pre-topk 1000 \
    --keep-topk 100 \
    --iou-threshold 0.65 \
    --score-threshold 0.25
```
### export CPU onnx
14.inference by cpu onnx
```
!cd .. && python projects/easydeploy/tools/image-demo.py \
        data/cat/images/IMG_20210728_205312.jpg \
        configs/yolov5/yolov5_s-v61_fast_1xb12-40e_cat.py \
        work_dirs/yolov5_s-v61_fast_1xb12-40e_cat/epoch_40.onnx \
        --device cpu
```
### export tensorRT engine
15.export cuda:0 onnx
```
!cd .. && python projects/easydeploy/tools/export_onnx.py \
    configs/yolov5/yolov5_s-v61_fast_1xb12-40e_cat.py \
    work_dirs/yolov5_s-v61_fast_1xb12-40e_cat/epoch_40.pth \
    --work-dir work_dirs/yolov5_s-v61_fast_1xb12-40e_cat \
    --img-size 640 640 \
    --batch 1 \
    --device cuda:0 \
    --simplify \
    --opset 11 \
    --backend TENSORRT8 \
    --pre-topk 1000 \
    --keep-topk 100 \
    --iou-threshold 0.65 \
    --score-threshold 0.25
```
16.export tensorRT engine
```
!cd .. && python projects/easydeploy/tools/build_engine.py \
        work_dirs/yolov5_s-v61_fast_1xb12-40e_cat/epoch_40.onnx \
        --img-size 640 640 \
        --device cuda:0
```
17.inference image by tensorRT engine
```
!cd .. && python projects/easydeploy/tools/image-demo.py \
        data/cat/images/IMG_20210728_205312.jpg \
        configs/yolov5/yolov5_s-v61_fast_1xb12-40e_cat.py \
        work_dirs/yolov5_s-v61_fast_1xb12-40e_cat/epoch_40.engine \
        --device cuda:0
```
18.All the inference image results are in `/mmyolo/output`

## Env
```
------------------------------------------------------------
System environment:
    sys.platform: linux
    Python: 3.7.10 (default, Feb 26 2021, 18:47:35) [GCC 7.3.0]
    CUDA available: True
    numpy_random_seed: 1121750788
    GPU 0: NVIDIA GeForce RTX 3090
    CUDA_HOME: /usr/local/cuda
    NVCC: Cuda compilation tools, release 11.1, V11.1.105
    GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
    PyTorch: 1.9.0
    PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.2-Product Build 20210312 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.1.2 (Git Hash 98be7e8afa711dc9b66c8ff3504129cb82013cdb)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.9.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

    TorchVision: 0.10.0
    OpenCV: 4.9.0
    MMEngine: 0.10.2

Runtime environment:
    cudnn_benchmark: True
    mp_cfg: {'mp_start_method': 'fork', 'opencv_num_threads': 0}
    dist_cfg: {'backend': 'nccl'}
    seed: 1121750788
    Distributed launcher: none
    Distributed training: False
    GPU number: 1
------------------------------------------------------------
```

## Hope it will help anyone and my mmyolo repo is https://github.com/keeper-jie/mmyolo

**Comment by Tkk0124** [comment]
ValueError: '2' is not a valid MMYOLOBackend，请问这个问题解决了吗？

**Comment by TtopsBo** [comment]
> ValueError: '2' is not a valid MMYOLOBackend，请问这个问题解决了吗？
改成TENSORRT8
