### ISSUE TITLE
demo/boxam_vis_demo.py not work for yolo-x

### ISSUE THREAD

**Issue by chenslcool** [open-mmlab/mmyolo#925]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmyolo/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmyolo.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmyolo).

### 🐞 Describe the bug

I want to generate boxcam for yolo-x. however,demo/boxam_vis_demo.py failed, I think it may be caused by different loss_by_feat between yolox and yolov5. But I don't know how to fix it.

The bug report is :
The algorithm currently used is yolox
Loads checkpoint by local backend from path: work_dir_480/yolox_l/fold0/best_coco_bbox_mAP_epoch_28.pth
[                                                  ] 0/1, elapsed: 0s, ETA:/home/chensl/miniconda3/envs/mm3/lib/python3.8/site-packages/torch/nn/functional.py:3454: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  warnings.warn(
Traceback (most recent call last):
  File "demo/boxam_vis_demo.py", line 276, in <module>
    main()
  File "demo/boxam_vis_demo.py", line 239, in main
    grayscale_boxam = boxam_detector_visualizer(image, targets=targets)
  File "/home/chensl/mmyolo-main/mmyolo/utils/boxam_utils.py", line 287, in __call__
    return self.cam(img, targets, aug_smooth, eigen_smooth)[0, :]
  File "/home/chensl/miniconda3/envs/mm3/lib/python3.8/site-packages/pytorch_grad_cam/base_cam.py", line 188, in __call__
    return self.forward(input_tensor,
  File "/home/chensl/miniconda3/envs/mm3/lib/python3.8/site-packages/pytorch_grad_cam/base_cam.py", line 74, in forward
    outputs = self.activations_and_grads(input_tensor)
  File "/home/chensl/miniconda3/envs/mm3/lib/python3.8/site-packages/pytorch_grad_cam/activations_and_gradients.py", line 42, in __call__
    return self.model(x)
  File "/home/chensl/mmyolo-main/mmyolo/utils/boxam_utils.py", line 217, in __call__
    loss = self.detector._run_forward(data, mode='loss')
  File "/home/chensl/miniconda3/envs/mm3/lib/python3.8/site-packages/mmengine/model/base_model/base_model.py", line 346, in _run_forward
    results = self(**data, mode=mode)
  File "/home/chensl/miniconda3/envs/mm3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/chensl/mmdet3/mmdet/models/detectors/base.py", line 92, in forward
    return self.loss(inputs, data_samples)
  File "/home/chensl/mmdet3/mmdet/models/detectors/single_stage.py", line 78, in loss
    losses = self.bbox_head.loss(x, batch_data_samples)
  File "/home/chensl/mmyolo-main/mmyolo/models/dense_heads/yolov5_head.py", line 464, in loss
    losses = super().loss(x, batch_data_samples)
  File "/home/chensl/mmdet3/mmdet/models/dense_heads/base_dense_head.py", line 123, in loss
    losses = self.loss_by_feat(*loss_inputs)
  File "/home/chensl/mmyolo-main/mmyolo/models/dense_heads/yolox_head.py", line 300, in loss_by_feat
    batch_gt_instances = self.gt_instances_preprocess(
  File "/home/chensl/mmyolo-main/mmyolo/models/dense_heads/yolox_head.py", line 509, in gt_instances_preprocess
    batch_gt_instances[batch_gt_instances[:, 0] == i, :]
TypeError: list indices must be integers or slices, not tuple

Thanks!

### Environment

sys.platform: linux
Python: 3.8.18 (default, Sep 11 2023, 13:40:15) [GCC 11.2.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0,1,2,3: NVIDIA TITAN Xp
CUDA_HOME: /opt/cuda
NVCC: Cuda compilation tools, release 11.1, V11.1.105
GCC: gcc (Gentoo 10.3.0-r1 p2) 10.3.0
PyTorch: 1.8.1+cu111
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.9.1+cu111
OpenCV: 4.8.1
MMEngine: 0.9.0
MMCV: 2.0.0rc4
MMDetection: 3.2.0
MMYOLO: 0.6.0+5753361

### Additional information

I think it may be caused by different loss_by_feat between yolox and yolov5. But I don't know how to fix it.

**Comment by chenslcool** [comment]
solved. add if isinstance(batch_gt_instances,Tensor): before https://github.com/open-mmlab/mmyolo/blob/main/mmyolo/models/dense_heads/yolox_head.py#L300
