### ISSUE TITLE
ERROR: Could not build wheels for mmcv, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by Dominic-ZZ** [open-mmlab/mmyolo#994]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmyolo/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmyolo.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmyolo).

### 🐞 Describe the bug

This error occurred when I was configuring the environment and installing mmcv：`mim install "mmcv>=2.0.0rc4,<2.1.0"`
I used docker: `pytorch/pytorch:2.2.2-cuda12.1-cudnn8-devel`

Errors are as follows: (Please see the attachment for the complete content)
[error_.txt](https://github.com/open-mmlab/mmyolo/files/15037371/error_.txt)

```bash
root@e49d8683fcf1:/workspace# mim install "mmcv>=2.0.0rc4,<2.1.0"
Looking in links: https://download.openmmlab.com/mmcv/dist/cu121/torch2.2.0/index.html
Collecting mmcv<2.1.0,>=2.0.0rc4
  Downloading mmcv-2.0.1.tar.gz (469 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 469.5/469.5 kB 804.7 kB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: addict in /opt/conda/lib/python3.10/site-packages (from mmcv<2.1.0,>=2.0.0rc4) (2.4.0)
Requirement already satisfied: mmengine>=0.3.0 in /opt/conda/lib/python3.10/site-packages (from mmcv<2.1.0,>=2.0.0rc4) (0.10.3)
Requirement already satisfied: numpy in /opt/conda/lib/python3.10/site-packages (from mmcv<2.1.0,>=2.0.0rc4) (1.26.4)
Requirement already satisfied: packaging in /opt/conda/lib/python3.10/site-packages (from mmcv<2.1.0,>=2.0.0rc4) (23.2)
Requirement already satisfied: Pillow in /opt/conda/lib/python3.10/site-packages (from mmcv<2.1.0,>=2.0.0rc4) (10.2.0)
Requirement already satisfied: pyyaml in /opt/conda/lib/python3.10/site-packages (from mmcv<2.1.0,>=2.0.0rc4) (6.0.1)
Requirement already satisfied: yapf in /opt/conda/lib/python3.10/site-packages (from mmcv<2.1.0,>=2.0.0rc4) (0.40.2)
Requirement already satisfied: opencv-python>=3 in /opt/conda/lib/python3.10/site-packages (from mmcv<2.1.0,>=2.0.0rc4) (4.9.0.80)
Requirement already satisfied: matplotlib in /opt/conda/lib/python3.10/site-packages (from mmengine>=0.3.0->mmcv<2.1.0,>=2.0.0rc4) (3.8.4)
Requirement already satisfied: rich in /opt/conda/lib/python3.10/site-packages (from mmengine>=0.3.0->mmcv<2.1.0,>=2.0.0rc4) (13.4.2)
Requirement already satisfied: termcolor in /opt/conda/lib/python3.10/site-packages (from mmengine>=0.3.0->mmcv<2.1.0,>=2.0.0rc4) (2.4.0)
Requirement already satisfied: importlib-metadata>=6.6.0 in /opt/conda/lib/python3.10/site-packages (from yapf->mmcv<2.1.0,>=2.0.0rc4) (7.1.0)
Requirement already satisfied: platformdirs>=3.5.1 in /opt/conda/lib/python3.10/site-packages (from yapf->mmcv<2.1.0,>=2.0.0rc4) (3.10.0)
Requirement already satisfied: tomli>=2.0.1 in /opt/conda/lib/python3.10/site-packages (from yapf->mmcv<2.1.0,>=2.0.0rc4) (2.0.1)
Requirement already satisfied: zipp>=0.5 in /opt/conda/lib/python3.10/site-packages (from importlib-metadata>=6.6.0->yapf->mmcv<2.1.0,>=2.0.0rc4) (3.18.1)
Requirement already satisfied: contourpy>=1.0.1 in /opt/conda/lib/python3.10/site-packages (from matplotlib->mmengine>=0.3.0->mmcv<2.1.0,>=2.0.0rc4) (1.2.1)
Requirement already satisfied: cycler>=0.10 in /opt/conda/lib/python3.10/site-packages (from matplotlib->mmengine>=0.3.0->mmcv<2.1.0,>=2.0.0rc4) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /opt/conda/lib/python3.10/site-packages (from matplotlib->mmengine>=0.3.0->mmcv<2.1.0,>=2.0.0rc4) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/conda/lib/python3.10/site-packages (from matplotlib->mmengine>=0.3.0->mmcv<2.1.0,>=2.0.0rc4) (1.4.5)
Requirement already satisfied: pyparsing>=2.3.1 in /opt/conda/lib/python3.10/site-packages (from matplotlib->mmengine>=0.3.0->mmcv<2.1.0,>=2.0.0rc4) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in /opt/conda/lib/python3.10/site-packages (from matplotlib->mmengine>=0.3.0->mmcv<2.1.0,>=2.0.0rc4) (2.9.0.post0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /opt/conda/lib/python3.10/site-packages (from rich->mmengine>=0.3.0->mmcv<2.1.0,>=2.0.0rc4) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /opt/conda/lib/python3.10/site-packages (from rich->mmengine>=0.3.0->mmcv<2.1.0,>=2.0.0rc4) (2.15.1)
Requirement already satisfied: mdurl~=0.1 in /opt/conda/lib/python3.10/site-packages (from markdown-it-py>=2.2.0->rich->mmengine>=0.3.0->mmcv<2.1.0,>=2.0.0rc4) (0.1.2)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.10/site-packages (from python-dateutil>=2.7->matplotlib->mmengine>=0.3.0->mmcv<2.1.0,>=2.0.0rc4) (1.16.0)
Building wheels for collected packages: mmcv
  Building wheel for mmcv (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [118940 lines of output]
      running bdist_wheel
      /opt/conda/lib/python3.10/site-packages/torch/utils/cpp_extension.py:500: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
        warnings.warn(msg.format('we could not find ninja.'))
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-3.10
      creating build/lib.linux-x86_64-3.10/mmcv
      copying mmcv/version.py -> build/lib.linux-x86_64-3.10/mmcv
      copying mmcv/__init__.py -> build/lib.linux-x86_64-3.10/mmcv
      creating build/lib.linux-x86_64-3.10/mmcv/cnn
      copying mmcv/cnn/__init__.py -> build/lib.linux-x86_64-3.10/mmcv/cnn
      copying mmcv/cnn/resnet.py -> build/lib.linux-x86_64-3.10/mmcv/cnn
      copying mmcv/cnn/vgg.py -> build/lib.linux-x86_64-3.10/mmcv/cnn

```

### Environment

docker images: pytorch/pytorch:2.2.2-cuda12.1-cudnn8-devel

**Comment by Dominic-ZZ** [comment]
I tried to build a docker image with [Dockerfile](https://github.com/open-mmlab/mmyolo/blob/main/docker/Dockerfile), but occured another error: 
```bash
[+] Building 6028.9s (7/9)                                                                                                                                                                                                                                           docker:default
 => [internal] load build definition from Dockerfile                                                                                                                                                                                                                           0.1s
 => => transferring dockerfile: 1.44kB                                                                                                                                                                                                                                         0.0s
 => [internal] load .dockerignore                                                                                                                                                                                                                                              0.1s
 => => transferring context: 2B                                                                                                                                                                                                                                                0.0s
 => [internal] load metadata for docker.io/pytorch/pytorch:1.9.0-cuda11.1-cudnn8-devel                                                                                                                                                                                         4.4s
 => [1/6] FROM docker.io/pytorch/pytorch:1.9.0-cuda11.1-cudnn8-devel@sha256:ed167cae955fa654cefc3663fc0c7b16ee9c8e7ed307cb03306d6ea7a9f7b37b                                                                                                                                2766.3s
 => => resolve docker.io/pytorch/pytorch:1.9.0-cuda11.1-cudnn8-devel@sha256:ed167cae955fa654cefc3663fc0c7b16ee9c8e7ed307cb03306d6ea7a9f7b37b                                                                                                                                   0.0s
 => => sha256:3cf8fb62ba5ffb221a2edb2208741346eb4d2d99a174138e4afbb69ce1fd9966 850B / 850B                                                                                                                                                                                     1.7s
 => => sha256:f22ccc0b8772d8e1bcb40f137b373686bc27427a70c0e41dd22b38016e09e7e0 26.71MB / 26.71MB                                                                                                                                                                              30.8s
 => => sha256:ed167cae955fa654cefc3663fc0c7b16ee9c8e7ed307cb03306d6ea7a9f7b37b 2.85kB / 2.85kB                                                                                                                                                                                 0.0s
 => => sha256:c35f519fe286f089f9728277fadcd8991ead8c80038cf0026f851292bdd7b97a 11.01kB / 11.01kB                                                                                                                                                                               0.0s
 => => sha256:e80c964ece6a3edf0db1cfc72ae0e6f0699fb776bbfcc92b708fbb945b0b9547 162B / 162B                                                                                                                                                                                     1.8s
 => => sha256:8a451ac89a8770e7511bef46164b1f1b96015a791cba6d297088ec681fce8213 7.23MB / 7.23MB                                                                                                                                                                                15.2s
 => => sha256:c563160b1f64ba99cf3ac166cd25ff822765048448ae4123346112b5f19bc6a5 10.79MB / 10.79MB                                                                                                                                                                              16.9s
 => => sha256:596a4690220219e331c201ef52e442e820b1c370584d0952e99898b0b1f16675 185B / 185B                                                                                                                                                                                    16.3s
 => => sha256:aa080598318088b68f055d203cf43facdcacf51058402a960e24eaddcec45d3f 1.50GB / 1.50GB                                                                                                                                                                               701.5s
 => => sha256:5718c3da35a08d73c5fb739246d85d4df1fcc4cb4e57661de3fcd1deaf41e518 1.24GB / 1.24GB                                                                                                                                                                               630.0s
 => => extracting sha256:f22ccc0b8772d8e1bcb40f137b373686bc27427a70c0e41dd22b38016e09e7e0                                                                                                                                                                                      0.7s
 => => sha256:003637b0851ab1784bf5024db8e7fa24752a57518019ac341e0a885bb4b24128 1.57GB / 1.57GB                                                                                                                                                                               776.4s
 => => extracting sha256:3cf8fb62ba5ffb221a2edb2208741346eb4d2d99a174138e4afbb69ce1fd9966                                                                                                                                                                                      0.0s
 => => extracting sha256:e80c964ece6a3edf0db1cfc72ae0e6f0699fb776bbfcc92b708fbb945b0b9547                                                                                                                                                                                      0.0s
 => => extracting sha256:8a451ac89a8770e7511bef46164b1f1b96015a791cba6d297088ec681fce8213                                                                                                                                                                                      0.2s
 => => extracting sha256:c563160b1f64ba99cf3ac166cd25ff822765048448ae4123346112b5f19bc6a5                                                                                                                                                                                      0.1s
 => => extracting sha256:596a4690220219e331c201ef52e442e820b1c370584d0952e99898b0b1f16675                                                                                                                                                                                      0.0s
 => => sha256:6a0071256cddf29c5c32b2e7e01c39a1ae95a64e47f4be6cd7c919bb3295a81e 1.43MB / 1.43MB                                                                                                                                                                               633.3s
 => => sha256:66d4bed311a2a65b52f2c67167316b79b7fac58b8d3de9b230c37961bc714c15 3.74GB / 3.74GB                                                                                                                                                                              2727.3s
 => => extracting sha256:aa080598318088b68f055d203cf43facdcacf51058402a960e24eaddcec45d3f                                                                                                                                                                                     11.2s
 => => sha256:82a5ac9ac621bb55ada3fd44572cecd6ccbadf7e9c9fa36c99b46e465ef699ff 132B / 132B                                                                                                                                                                                   702.9s
 => => extracting sha256:5718c3da35a08d73c5fb739246d85d4df1fcc4cb4e57661de3fcd1deaf41e518                                                                                                                                                                                     11.1s
 => => extracting sha256:003637b0851ab1784bf5024db8e7fa24752a57518019ac341e0a885bb4b24128                                                                                                                                                                                     19.8s
 => => extracting sha256:6a0071256cddf29c5c32b2e7e01c39a1ae95a64e47f4be6cd7c919bb3295a81e                                                                                                                                                                                      0.1s
 => => extracting sha256:66d4bed311a2a65b52f2c67167316b79b7fac58b8d3de9b230c37961bc714c15                                                                                                                                                                                     38.2s
 => => extracting sha256:82a5ac9ac621bb55ada3fd44572cecd6ccbadf7e9c9fa36c99b46e465ef699ff                                                                                                                                                                                      0.0s
 => [2/6] RUN rm /etc/apt/sources.list.d/cuda.list     && rm /etc/apt/sources.list.d/nvidia-ml.list     && apt-key del 7fa2af80     && apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/3bf863cc.pub     && apt-key adv -  18.4s
 => [3/6] RUN apt-get update     && apt-get install -y ffmpeg libsm6 libxext6 git ninja-build libglib2.0-0 libxrender-dev     && apt-get clean     && rm -rf /var/lib/apt/lists/*                                                                                            854.9s
 => ERROR [4/6] RUN pip install --no-cache-dir openmim &&     mim install --no-cache-dir "mmengine>=0.6.0" "mmcv>=2.0.0rc4,<2.1.0" "mmdet>=3.0.0,<4.0.0"                                                                                                                    2384.8s
------
 > [4/6] RUN pip install --no-cache-dir openmim &&     mim install --no-cache-dir "mmengine>=0.6.0" "mmcv>=2.0.0rc4,<2.1.0" "mmdet>=3.0.0,<4.0.0":
0.916 Collecting openmim
1.445   Downloading openmim-0.3.9-py2.py3-none-any.whl (52 kB)
2.126 Collecting rich
2.508   Downloading rich-13.7.1-py3-none-any.whl (240 kB)
6.503 Requirement already satisfied: pip>=19.3 in /opt/conda/lib/python3.7/site-packages (from openmim) (21.1.2)
6.876 Collecting model-index
6.975   Downloading model_index-0.1.11-py3-none-any.whl (34 kB)
8.920 Collecting pandas
9.030   Downloading pandas-1.3.5-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.3 MB)
253.9 Requirement already satisfied: requests in /opt/conda/lib/python3.7/site-packages (from openmim) (2.24.0)
254.0 Collecting colorama
254.8   Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
255.8 Collecting Click
255.9   Downloading click-8.1.7-py3-none-any.whl (97 kB)
258.3 Collecting tabulate
258.4   Downloading tabulate-0.9.0-py3-none-any.whl (35 kB)
259.7 Collecting opendatalab
260.4   Downloading opendatalab-0.0.10-py3-none-any.whl (29 kB)
261.1 Collecting importlib-metadata
261.2   Downloading importlib_metadata-6.7.0-py3-none-any.whl (22 kB)
262.4 Requirement already satisfied: typing-extensions>=3.6.4 in /opt/conda/lib/python3.7/site-packages (from importlib-metadata->Click->openmim) (3.7.4.3)
262.6 Collecting zipp>=0.5
262.6   Downloading zipp-3.15.0-py3-none-any.whl (6.8 kB)
263.1 Requirement already satisfied: pyyaml in /opt/conda/lib/python3.7/site-packages (from model-index->openmim) (5.4.1)
263.2 Collecting ordered-set
263.3   Downloading ordered_set-4.1.0-py3-none-any.whl (7.6 kB)
263.8 Collecting markdown
263.9   Downloading Markdown-3.4.4-py3-none-any.whl (94 kB)
270.2 Collecting pycryptodome
270.3   Downloading pycryptodome-3.20.0-cp35-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.1 MB)
314.5 Collecting openxlab
314.6   Downloading openxlab-0.0.10-py3-none-any.whl (32 kB)
315.3 Requirement already satisfied: tqdm in /opt/conda/lib/python3.7/site-packages (from opendatalab->openmim) (4.51.0)
315.3 Requirement already satisfied: idna<3,>=2.5 in /opt/conda/lib/python3.7/site-packages (from requests->openmim) (2.10)
315.3 Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.7/site-packages (from requests->openmim) (2021.5.30)
315.3 Requirement already satisfied: chardet<4,>=3.0.2 in /opt/conda/lib/python3.7/site-packages (from requests->openmim) (3.0.4)
315.3 Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /opt/conda/lib/python3.7/site-packages (from requests->openmim) (1.25.11)
315.8 Collecting requests
315.9   Downloading requests-2.28.2-py3-none-any.whl (62 kB)
317.5 Collecting oss2~=2.17.0
317.6   Downloading oss2-2.17.0.tar.gz (259 kB)
325.1 Collecting setuptools~=60.2.0
325.2   Downloading setuptools-60.2.0-py3-none-any.whl (953 kB)
344.9 Collecting pytz~=2023.3
345.0   Downloading pytz-2023.4-py2.py3-none-any.whl (506 kB)
360.2 Collecting pyyaml
360.3   Downloading PyYAML-6.0.1-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (670 kB)
373.4 Collecting tqdm
373.5   Downloading tqdm-4.65.2-py3-none-any.whl (77 kB)
375.2 Collecting crcmod>=1.7
375.3   Downloading crcmod-1.7.tar.gz (89 kB)
377.3 Collecting aliyun-python-sdk-kms>=2.4.1
377.4   Downloading aliyun_python_sdk_kms-2.16.2-py2.py3-none-any.whl (94 kB)
380.0 Collecting aliyun-python-sdk-core>=2.13.12
380.1   Downloading aliyun-python-sdk-core-2.15.1.tar.gz (443 kB)
387.1 Requirement already satisfied: six in /opt/conda/lib/python3.7/site-packages (from oss2~=2.17.0->openxlab->opendatalab->openmim) (1.16.0)
387.4 Collecting jmespath<1.0.0,>=0.9.3
387.5   Downloading jmespath-0.10.0-py2.py3-none-any.whl (24 kB)
388.3 Requirement already satisfied: cryptography>=2.6.0 in /opt/conda/lib/python3.7/site-packages (from aliyun-python-sdk-core>=2.13.12->oss2~=2.17.0->openxlab->opendatalab->openmim) (3.4.7)
388.3 Requirement already satisfied: cffi>=1.12 in /opt/conda/lib/python3.7/site-packages (from cryptography>=2.6.0->aliyun-python-sdk-core>=2.13.12->oss2~=2.17.0->openxlab->opendatalab->openmim) (1.14.5)
388.3 Requirement already satisfied: pycparser in /opt/conda/lib/python3.7/site-packages (from cffi>=1.12->cryptography>=2.6.0->aliyun-python-sdk-core>=2.13.12->oss2~=2.17.0->openxlab->opendatalab->openmim) (2.20)
390.7 Collecting charset-normalizer<4,>=2
390.8   Downloading charset_normalizer-3.3.2-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (136 kB)
395.6 Collecting python-dateutil>=2.7.3
395.7   Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
399.9 Requirement already satisfied: numpy>=1.17.3 in /opt/conda/lib/python3.7/site-packages (from pandas->openmim) (1.20.2)
400.2 Collecting pygments<3.0.0,>=2.13.0
400.5   Downloading pygments-2.17.2-py3-none-any.whl (1.2 MB)
425.3 Collecting markdown-it-py>=2.2.0
425.4   Downloading markdown_it_py-2.2.0-py3-none-any.whl (84 kB)
427.0 Collecting typing-extensions>=3.6.4
427.1   Downloading typing_extensions-4.7.1-py3-none-any.whl (33 kB)
427.8 Collecting mdurl~=0.1
427.9   Downloading mdurl-0.1.2-py3-none-any.whl (10.0 kB)
428.2 Building wheels for collected packages: oss2, aliyun-python-sdk-core, crcmod
428.2   Building wheel for oss2 (setup.py): started
428.3   Building wheel for oss2 (setup.py): finished with status 'done'
428.3   Created wheel for oss2: filename=oss2-2.17.0-py3-none-any.whl size=112394 sha256=604b9019a9f764a0269b6343821ce685d02818de7701f8928c38b2b6548cbea5
428.3   Stored in directory: /tmp/pip-ephem-wheel-cache-7m76gozv/wheels/02/ee/14/ae006e5f19929917bb138de44d7b26f9c1e962fcd5d96d196e
428.4   Building wheel for aliyun-python-sdk-core (setup.py): started
428.5   Building wheel for aliyun-python-sdk-core (setup.py): finished with status 'done'
428.5   Created wheel for aliyun-python-sdk-core: filename=aliyun_python_sdk_core-2.15.1-py3-none-any.whl size=535317 sha256=db8ea4e6a7129db3c8f85f5e9ac773ef15b2e86e81072d5e004a4d9a17556bce
428.5   Stored in directory: /tmp/pip-ephem-wheel-cache-7m76gozv/wheels/f1/37/36/1da3ed15c7d78406bfede104eb4eb9ea4ab1c75caa180b7966
428.5   Building wheel for crcmod (setup.py): started
428.8   Building wheel for crcmod (setup.py): finished with status 'done'
428.8   Created wheel for crcmod: filename=crcmod-1.7-cp37-cp37m-linux_x86_64.whl size=36506 sha256=aa89b7d88572973a7acd752fd4b67cd5155b9a09984fe6878db1609bdc7cb6f8
428.8   Stored in directory: /tmp/pip-ephem-wheel-cache-7m76gozv/wheels/dc/9a/e9/49e627353476cec8484343c4ab656f1e0d783ee77b9dde2d1f
428.8 Successfully built oss2 aliyun-python-sdk-core crcmod
429.0 Installing collected packages: jmespath, charset-normalizer, aliyun-python-sdk-core, zipp, typing-extensions, requests, pycryptodome, mdurl, crcmod, aliyun-python-sdk-kms, tqdm, setuptools, pyyaml, pytz, pygments, oss2, markdown-it-py, importlib-metadata, rich, python-d
ateutil, ordered-set, openxlab, markdown, colorama, Click, tabulate, pandas, opendatalab, model-index, openmim
429.2   Attempting uninstall: typing-extensions
429.2     Found existing installation: typing-extensions 3.7.4.3
429.2     Uninstalling typing-extensions-3.7.4.3:
429.2       Successfully uninstalled typing-extensions-3.7.4.3
429.3   Attempting uninstall: requests
429.3     Found existing installation: requests 2.24.0
429.3     Uninstalling requests-2.24.0:
429.3       Successfully uninstalled requests-2.24.0
429.6   Attempting uninstall: tqdm
429.6     Found existing installation: tqdm 4.51.0
429.6     Uninstalling tqdm-4.51.0:
429.6       Successfully uninstalled tqdm-4.51.0
429.6   Attempting uninstall: setuptools
429.6     Found existing installation: setuptools 52.0.0.post20210125
429.6     Uninstalling setuptools-52.0.0.post20210125:
429.7       Successfully uninstalled setuptools-52.0.0.post20210125
429.8   Attempting uninstall: pyyaml
429.8     Found existing installation: PyYAML 5.4.1
429.8     Uninstalling PyYAML-5.4.1:
429.9       Successfully uninstalled PyYAML-5.4.1
429.9   Attempting uninstall: pytz
429.9     Found existing installation: pytz 2021.1
429.9     Uninstalling pytz-2021.1:
430.0       Successfully uninstalled pytz-2021.1
430.0   Attempting uninstall: pygments
430.0     Found existing installation: Pygments 2.9.0
430.1     Uninstalling Pygments-2.9.0:
430.1       Successfully uninstalled Pygments-2.9.0
432.5 WARNING: Running pip as root will break packages and permissions. You should install packages reliably by using venv: https://pip.pypa.io/warnings/venv
432.5 Successfully installed Click-8.1.7 aliyun-python-sdk-core-2.15.1 aliyun-python-sdk-kms-2.16.2 charset-normalizer-3.3.2 colorama-0.4.6 crcmod-1.7 importlib-metadata-6.7.0 jmespath-0.10.0 markdown-3.4.4 markdown-it-py-2.2.0 mdurl-0.1.2 model-index-0.1.11 opendatalab-0.0.1
0 openmim-0.3.9 openxlab-0.0.10 ordered-set-4.1.0 oss2-2.17.0 pandas-1.3.5 pycryptodome-3.20.0 pygments-2.17.2 python-dateutil-2.9.0.post0 pytz-2023.4 pyyaml-6.0.1 requests-2.28.2 rich-13.7.1 setuptools-60.2.0 tabulate-0.9.0 tqdm-4.65.2 typing-extensions-4.7.1 zipp-3.15.0
433.8 Looking in links: https://download.openmmlab.com/mmcv/dist/cu111/torch1.9.0/index.html
434.6 Collecting mmengine>=0.6.0
435.9   Downloading mmengine-0.10.3-py3-none-any.whl (451 kB)
458.4 Collecting mmcv<2.1.0,>=2.0.0rc4
458.7   Downloading https://download.openmmlab.com/mmcv/dist/cu111/torch1.9.0/mmcv-2.0.1-cp37-cp37m-manylinux1_x86_64.whl (77.6 MB)
463.6 Collecting mmdet<4.0.0,>=3.0.0
463.7   Downloading mmdet-3.3.0-py3-none-any.whl (2.2 MB)
557.7 Requirement already satisfied: rich in /opt/conda/lib/python3.7/site-packages (from mmengine>=0.6.0) (13.7.1)
557.8 Collecting addict
557.9   Downloading addict-2.4.0-py3-none-any.whl (3.8 kB)
558.5 Collecting opencv-python>=3
558.6   Downloading opencv_python-4.9.0.80-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (62.2 MB)
2384.0 ERROR: Exception:
2384.0 Traceback (most recent call last):
2384.0   File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 438, in _error_catcher
2384.0     yield
2384.0   File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 519, in read
2384.0     data = self._fp.read(amt) if not fp_closed else b""
2384.0   File "/opt/conda/lib/python3.7/http/client.py", line 461, in read
2384.0     n = self.readinto(b)
2384.0   File "/opt/conda/lib/python3.7/http/client.py", line 505, in readinto
2384.0     n = self.fp.readinto(b)
2384.0   File "/opt/conda/lib/python3.7/socket.py", line 589, in readinto
2384.0     return self._sock.recv_into(b)
2384.0   File "/opt/conda/lib/python3.7/ssl.py", line 1071, in recv_into
2384.0     return self.read(nbytes, buffer)
2384.0   File "/opt/conda/lib/python3.7/ssl.py", line 929, in read
2384.0     return self._sslobj.read(len, buffer)
2384.0 socket.timeout: The read operation timed out
2384.0
2384.0 During handling of the above exception, another exception occurred:
2384.0
2384.0 Traceback (most recent call last):
2384.0   File "/opt/conda/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 180, in _main
2384.0     status = self.run(options, args)
2384.0   File "/opt/conda/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 204, in wrapper
2384.0     return func(self, options, args)
2384.0   File "/opt/conda/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 319, in run
2384.0     reqs, check_supported_wheels=not options.target_dir
2384.0   File "/opt/conda/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 128, in resolve
2384.0     requirements, max_rounds=try_to_avoid_resolution_too_deep
2384.0   File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 473, in resolve
2384.0     state = resolution.resolve(requirements, max_rounds=max_rounds)
2384.0   File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 367, in resolve
2384.0     failure_causes = self._attempt_to_pin_criterion(name)
2384.0   File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 213, in _attempt_to_pin_criterion
2384.0     criteria = self._get_criteria_to_update(candidate)
2384.0   File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 203, in _get_criteria_to_update
2384.0     name, crit = self._merge_into_criterion(r, parent=candidate)
2384.0   File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 172, in _merge_into_criterion
2384.0     if not criterion.candidates:
2384.0   File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/resolvelib/structs.py", line 139, in __bool__
2384.0     return bool(self._sequence)
2384.0   File "/opt/conda/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in __bool__
2384.0     return any(self)
2384.0   File "/opt/conda/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 129, in <genexpr>
2384.0     return (c for c in iterator if id(c) not in self._incompatible_ids)
2384.0   File "/opt/conda/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 33, in _iter_built
2384.0     candidate = func()
2384.0   File "/opt/conda/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 205, in _make_candidate_from_link
2384.0     version=version,
2384.0   File "/opt/conda/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 312, in __init__
2384.0     version=version,
2384.0   File "/opt/conda/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 151, in __init__
2384.0     self.dist = self._prepare()
2384.0   File "/opt/conda/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 234, in _prepare
2384.0     dist = self._prepare_distribution()
2384.0   File "/opt/conda/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 318, in _prepare_distribution
2384.0     self._ireq, parallel_builds=True
2384.0   File "/opt/conda/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 508, in prepare_linked_requirement
2384.0     return self._prepare_linked_requirement(req, parallel_builds)
2384.0   File "/opt/conda/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 552, in _prepare_linked_requirement
2384.0     self.download_dir, hashes
2384.0   File "/opt/conda/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 243, in unpack_url
2384.0     hashes=hashes,
2384.0   File "/opt/conda/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 102, in get_http_url
2384.0     from_path, content_type = download(link, temp_dir.path)
2384.0   File "/opt/conda/lib/python3.7/site-packages/pip/_internal/network/download.py", line 157, in __call__
2384.0     for chunk in chunks:
2384.0   File "/opt/conda/lib/python3.7/site-packages/pip/_internal/cli/progress_bars.py", line 152, in iter
2384.0     for x in it:
2384.0   File "/opt/conda/lib/python3.7/site-packages/pip/_internal/network/utils.py", line 86, in response_chunks
2384.0     decode_content=False,
2384.0   File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 576, in stream
2384.0     data = self.read(amt=amt, decode_content=decode_content)
2384.0   File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 541, in read
2384.0     raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
2384.0   File "/opt/conda/lib/python3.7/contextlib.py", line 130, in __exit__
2384.0     self.gen.throw(type, value, traceback)
2384.0   File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 443, in _error_catcher
2384.0     raise ReadTimeoutError(self._pool, None, "Read timed out.")
2384.0 pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
------
Dockerfile:28
--------------------
  27 |     # Install MMEngine , MMCV and MMDet
  28 | >>> RUN pip install --no-cache-dir openmim && \
  29 | >>>     mim install --no-cache-dir "mmengine>=0.6.0" "mmcv>=2.0.0rc4,<2.1.0" "mmdet>=3.0.0,<4.0.0"
  30 |
--------------------
ERROR: failed to solve: process "/bin/sh -c pip install --no-cache-dir openmim &&     mim install --no-cache-dir \"mmengine>=0.6.0\" \"mmcv>=2.0.0rc4,<2.1.0\" \"mmdet>=3.0.0,<4.0.0\"" did not complete successfully: exit code: 2

```

**Comment by hitbg-yjm** [comment]
maybe your pytorch version is too high，use this commond:
conda create -n mmyolo python=3.8 pytorch==1.10.1 torchvision==0.11.2 cudatoolkit=11.3 -c pytorch -y
